/* EarthVisited — click the countries you've been to.
   Data comes from js/data.js (generated by tools/gen.mjs):
     WORLD = { w, h, decor:[pathData], f:[ {c,n,t,g,r,s,a,x,y,d} ] }
     c=ISO alpha-2  n=English name  t=Turkish name  g=flag  r=region
     s=1 sovereign / 2 territory    a=projected area  x,y=centroid  d=SVG path
*/
(() => {
  'use strict';

  const SVG_NS = 'http://www.w3.org/2000/svg';
  const STORE_KEY = 'earthvisited:v1';
  const PREF_KEY = 'earthvisited:prefs';
  const SUB_KEY = 'earthvisited:sub1'; // provinces, kept apart from the country marks
  const CITY_KEY = 'earthvisited:cities';
  const DOT_AREA = 6; // entities smaller than this get a clickable dot
  const DRAG_SLOP = 4; // px of movement before a press counts as a pan, not a tap
  const MAX_ZOOM = 24; // past this the 1:50m coastlines run out of detail
  // an open country is drawn from 1:10m geometry, which holds up much closer — and
  // fitting a small country to the panel can already cost more than 24x
  const DETAIL_ZOOM = 160;
  const maxZoom = () => (detail ? DETAIL_ZOOM : MAX_ZOOM);

  const W = WORLD.w;
  const H = WORLD.h;
  // paths are baked at WORLD.ps times this coordinate space, as integers, and drawn
  // inside a group that scales them back down — everything else stays in W x H units
  const PATH_SCALE = WORLD.ps || 1;
  const FEATURES = WORLD.f;
  const byCode = new Map(FEATURES.map((f) => [f.c, f]));
  // s: 1 UN member (or observer state), 3 counted as a country anyway, 2 territory
  const isCountry = (f) => f.s === 1 || f.s === 3;
  const SOVEREIGN_TOTAL = FEATURES.filter(isCountry).length;
  const WORLD_LAND = WORLD.totals.k; // km², every entity on the map
  const WORLD_POP = WORLD.totals.p;
  // Bit order for share links. data.js pins it so that entities added later land at
  // the end and older links keep decoding to the same countries.
  const SHARE_ORDER = WORLD.order || FEATURES.map((f) => f.c).sort();

  const REGION_BOX = WORLD.regions;
  const REGIONS = ['Africa', 'Americas', 'Asia', 'Europe', 'Oceania'];
  const REGION_TOTAL = {};
  for (const r of REGIONS) REGION_TOTAL[r] = FEATURES.filter((f) => isCountry(f) && f.r === r).length;

  /* ---------------- i18n ---------------- */
  const LANGS = I18N.list;
  const STRINGS = I18N.s;
  const REGION_NAMES = I18N.regions;
  const DEFAULT_COLORS = {}; // filled from the stylesheet on first paint

  let lang = 'en';
  let theme = 'auto'; // 'dark' | 'light' | 'auto'
  let colors = {}; // level id -> custom hex, empty means the stylesheet default
  const t = (k) => STRINGS[lang][k] ?? STRINGS.en[k] ?? k;
  const nameOf = (f) => (f.L && f.L[lang]) || f.n;
  const localeOf = () => (LANGS.find((l) => l.code === lang) || LANGS[0]).locale;

  /* ---------------- state ---------------- */
  // 0 = unmarked. 1..3 all mean "I have been there" and feed the score; 4 is a wish.
  const LEVELS = [
    { id: 1, key: 'lived' },
    { id: 2, key: 'visited' },
    { id: 3, key: 'transit' },
    { id: 4, key: 'wish' },
  ];
  const BEEN = new Set([1, 2, 3]);
  const marks = new Map(); // code -> level
  let brush = 2; // the level a click paints with
  const been = (code) => BEEN.has(marks.get(code));
  const els = {}; // code -> { shape, row }
  let activeRegion = null; // continent filter, or null for the whole world
  let regionCounts = {};
  let lastCounts = null;
  let resetArmed = false;
  let resetTimer;
  let animTimer;
  let mode = 'map'; // which view is on screen: 'map' | 'globe'
  // and what the view is made of: whole countries, or the provinces inside them.
  // The two are independent — the globe has both, and so does the flat map.
  let grain = 'country'; // 'country' | 'sub'
  const subMarks = new Map(); // 'TR-34' -> level, provinces of every country
  const cityMarks = new Map(); // geonameid -> level
  let detail = null; // { code, units, byId, box, group } while a country is open
  let globeLoading = null; // promise while the globe bundle is loading
  let cardSize = 'link';
  let cardBlob = null; // PNG for the size currently previewed

  const $ = (id) => document.getElementById(id);
  // The score line's world markup, kept from before anything can overwrite it: a
  // country's provinces and the city view both write plain text over it, and the
  // spans inside (the city counter) have to come back intact.
  let worldSubtitle = null;

  // Most flags are emoji; entities without one (Northern Cyprus) ship an SVG.
  function flagNode(f, cls = 'flag') {
    if (f.fi) {
      const img = document.createElement('img');
      img.className = cls;
      img.src = f.fi;
      img.alt = '';
      return img;
    }
    const span = document.createElement('span');
    span.className = cls;
    span.textContent = f.g || '🏳';
    return span;
  }
  const map = $('map');
  const mapwrap = $('mapwrap');
  const tip = $('tip');
  const list = $('list');

  /* ---------------- persistence ---------------- */
  const encodeShare = () => Share.encode(SHARE_ORDER, marks);
  const decodeShare = (str) => Share.decode(SHARE_ORDER, str);
  const decodeShareV1 = (str) => Share.decodeV1(SHARE_ORDER, str);

  function save() {
    try {
      localStorage.setItem(STORE_KEY, [...marks].map(([c, lv]) => c + lv).join(','));
      localStorage.setItem(SUB_KEY, [...subMarks].map(([c, lv]) => `${c}:${lv}`).join(','));
      localStorage.setItem(CITY_KEY, [...cityMarks].map(([id, lv]) => `${id}:${lv}`).join(','));
    } catch { /* private mode */ }
  }

  function savePrefs() {
    try {
      localStorage.setItem(PREF_KEY, JSON.stringify({ lang, theme, colors, view: mode, grain }));
    } catch { /* private mode */ }
  }

  function fromHash() {
    const m = location.hash.match(/^#v([12])=([\w-]+)/);
    if (!m) return null;
    const list = m[1] === '2' ? decodeShare(m[2]) : decodeShareV1(m[2]);
    return list && list.length ? list : null;
  }

  // provinces travel in a &p= section: one part per country, so a link only grows
  // for the countries actually opened
  function subFromHash() {
    const m = location.hash.match(/[#&]p=([\w~.-]+)/);
    return m ? m[1] : null;
  }

  function citiesFromHash() {
    const m = location.hash.match(/[#&]c=([\w-]+)/);
    return m ? m[1] : null;
  }

  // the detail and city files may not be loaded yet, so keep the sections until they are
  let pendingSub = null;
  let pendingCities = null;

  async function applyPendingSub() {
    if (!pendingSub) return;
    const countries = [...new Set(pendingSub.split('.').map((s) => s.split('~')[0]))];
    // provinces of a country without a detail file of its own are numbered by the
    // world layer, so that has to be here before the link can be read
    if (countries.some((c) => !hasDetail(c))) await ensureWorldSubs();
    await Promise.all(countries.filter(hasDetail).map(loadDetail));
    const list = Share.decodeSub(unitOrder(), pendingSub);
    pendingSub = null;
    if (!list || !list.length) return;
    subMarks.clear();
    for (const [id, lv] of list) subMarks.set(id, lv);
    save();
    if (detail) {
      for (const id of detail.byId.keys()) paintSub(id);
      updateScore();
    }
  }

  function load() {
    pendingSub = subFromHash();
    pendingCities = citiesFromHash();
    const shared = fromHash();
    if (shared) {
      shared.forEach(([c, lv]) => byCode.has(c) && marks.set(c, lv));
      return;
    }
    try {
      const rawSub = localStorage.getItem(SUB_KEY);
      if (rawSub) {
        for (const entry of rawSub.split(',')) {
          const [id, lv] = entry.split(':');
          if (id && +lv >= 1 && +lv <= 4) subMarks.set(id, +lv);
        }
      }
      const rawCities = localStorage.getItem(CITY_KEY);
      if (rawCities) {
        for (const entry of rawCities.split(',')) {
          const [id, lv] = entry.split(':');
          if (id && +lv >= 1 && +lv <= 4) cityMarks.set(+id, +lv);
        }
      }
      const raw = localStorage.getItem(STORE_KEY);
      if (!raw) return;
      for (const entry of raw.split(',')) {
        // entries are CODE + level; the pre-levels format stored a bare CODE
        const code = entry.slice(0, 2);
        const lv = entry.length > 2 ? +entry.slice(2) : 2;
        if (byCode.has(code) && lv >= 1 && lv <= 4) marks.set(code, lv);
      }
    } catch { /* private mode */ }
  }

  function loadPrefs() {
    let saved = null;
    try {
      saved = JSON.parse(localStorage.getItem(PREF_KEY) || 'null');
    } catch { /* ignore */ }
    const known = (c) => LANGS.some((l) => l.code === c);
    const systemLangs = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language];
    lang = I18N.pick(systemLangs, saved?.lang);
    theme = ['dark', 'light', 'auto'].includes(saved?.theme) ? saved.theme : 'auto';
    colors = saved && typeof saved.colors === 'object' && saved.colors ? { ...saved.colors } : {};
    // saved before the two were split, when "cities" was a view of its own
    mode = saved?.view === 'globe' ? 'globe' : 'map';
    grain = saved?.grain === 'sub' || saved?.view === 'cities' ? 'sub' : 'country';
    // ?lang=de / ?theme=light let a shared link pick how it opens
    const q = new URLSearchParams(location.search);
    if (known(q.get('lang'))) lang = q.get('lang');
    if (['dark', 'light', 'auto'].includes(q.get('theme'))) theme = q.get('theme');
    if (['globe', 'map'].includes(q.get('view'))) mode = q.get('view');
    if (q.get('view') === 'cities') grain = 'sub'; // links written before the split
    if (['country', 'sub'].includes(q.get('grain'))) grain = q.get('grain');
  }

  /* ---------------- map ---------------- */
  const scene = document.createElementNS(SVG_NS, 'g');
  scene.setAttribute('class', 'scene');

  function buildMap() {
    map.setAttribute('viewBox', `0 0 ${W} ${H}`);
    map.setAttribute('preserveAspectRatio', 'xMidYMid meet');

    const decorG = document.createElementNS(SVG_NS, 'g');
    for (const d of WORLD.decor) {
      const p = document.createElementNS(SVG_NS, 'path');
      p.setAttribute('d', d);
      p.setAttribute('class', 'land decor');
      decorG.appendChild(p);
    }

    const shapesG = document.createElementNS(SVG_NS, 'g');
    shapesG.setAttribute('transform', `scale(${1 / PATH_SCALE})`);
    const landG = document.createElementNS(SVG_NS, 'g');
    const dotG = document.createElementNS(SVG_NS, 'g');
    dotG.setAttribute('id', 'dots');
    const hitG = document.createElementNS(SVG_NS, 'g');
    hitG.setAttribute('id', 'hits');

    for (const f of FEATURES) {
      let shape;
      if (f.d) {
        shape = document.createElementNS(SVG_NS, 'path');
        shape.setAttribute('d', f.d);
        shape.setAttribute('class', 'land pickable');
        landG.appendChild(shape);
      }
      if (f.a < DOT_AREA) {
        const dot = document.createElementNS(SVG_NS, 'circle');
        dot.setAttribute('cx', f.x);
        dot.setAttribute('cy', f.y);
        dot.setAttribute('r', 2.6);
        dot.setAttribute('class', 'dot');
        dot.dataset.code = f.c;
        const hit = document.createElementNS(SVG_NS, 'circle');
        hit.setAttribute('cx', f.x);
        hit.setAttribute('cy', f.y);
        hit.setAttribute('r', 7);
        hit.setAttribute('class', 'hit');
        hit.dataset.code = f.c;
        hitG.appendChild(hit);
        els[f.c] = Object.assign(els[f.c] || {}, { hit });
        dotG.appendChild(dot);
        if (!shape) shape = dot;
        else els[f.c] = Object.assign(els[f.c] || {}, { extra: dot });
      }
      if (shape) shape.dataset.code = f.c;
      els[f.c] = Object.assign(els[f.c] || {}, { shape });
    }

    shapesG.append(decorG, landG);
    scene.append(shapesG, dotG, hitG);
    map.appendChild(scene);
    map.addEventListener('pointermove', onMapHover);
    map.addEventListener('pointerleave', hideTip);
  }

  // A micro-state's finger-sized target covers its neighbours: at world zoom the
  // whole of Germany is barely wider than Luxembourg's 18px circle. So a press on
  // one of those circles only counts as the micro-state when it lands on the dot
  // itself; otherwise the country underneath wins.
  // A tap does not always land on the shape under the finger: Chrome hit-tests a
  // touch as a rect and hands ambiguous ones to the container, which for a province
  // the size of a fingernail means the <svg> itself. The point is the truth.
  function subAt(e) {
    const direct = e.target.dataset && e.target.dataset.sub;
    if (direct) return direct;
    const found = document
      .elementsFromPoint(e.clientX, e.clientY)
      .find((el) => el.dataset && el.dataset.sub);
    return (found && found.dataset.sub) || null;
  }

  function codeAt(target, x, y) {
    const code = target && target.dataset && target.dataset.code;
    if (!code || !target.classList.contains('hit')) return code || null;
    const dot = els[code] && els[code].extra;
    if (dot) {
      // The hit circle is far wider than the dot it stands for. On a phone the whole
      // world is 370 px across, so Cyprus sits five pixels from the middle of
      // Anatolia — anything looser than the dot's own radius and a micro-state
      // swallows taps meant for the country underneath it.
      const r = dot.getBoundingClientRect();
      const near = Math.hypot(x - (r.left + r.width / 2), y - (r.top + r.height / 2));
      if (near <= Math.max(4, r.width / 2)) return code;
    } else {
      return code; // marker-only entity: the circle is all there is
    }
    const under = document.elementsFromPoint(x, y).find((el) => el.classList.contains('pickable'));
    return (under && under.dataset.code) || code;
  }

  function shapesOf(code) {
    const e = els[code];
    return e ? [e.shape, e.extra, e.hit].filter(Boolean) : [];
  }

  function paintShape(code) {
    const lv = marks.get(code) || 0;
    for (const el of shapesOf(code)) {
      el.classList.toggle('on', lv > 0);
      for (const l of LEVELS) el.classList.toggle(`lv${l.id}`, lv === l.id);
    }
  }

  /* ---------------- zoom & pan ---------------- */
  const view = { k: 1, x: 0, y: 0 };
  const pointers = new Map();
  let dragged = 0;
  let pinchStart = null;
  let pressCode = null;
  let pressSub = null;
  let pressCity = null;
  let pressTimer = null;
  let previewed = false; // a long press showed the name, so the release must not toggle

  function applyView() {
    view.x = Math.min(0, Math.max(W - W * view.k, view.x));
    view.y = Math.min(0, Math.max(H - H * view.k, view.y));
    scene.setAttribute('transform', `translate(${view.x} ${view.y}) scale(${view.k})`);
    sizeMarkers();
  }

  // Micro-state dots are sized in screen pixels, not map units: on a phone the whole
  // world is ~390px wide, so a fixed radius would shrink to a few pixels there.
  function sizeMarkers() {
    const pxPerUnit = ((map.getBoundingClientRect().width || W) / W) * view.k;
    if (!pxPerUnit) return;
    const dotR = Math.min(13, 3.6 / pxPerUnit);
    const hitR = Math.min(24, 9 / pxPerUnit);
    for (const dot of map.querySelectorAll('#dots circle')) dot.setAttribute('r', dotR);
    for (const hit of map.querySelectorAll('#hits circle')) hit.setAttribute('r', hitR);

    if (cityData && cityGroup) {
      // city coordinates live at their own scale, so the radius is divided by that
      // as well as by the zoom
      const r = Math.min(9, 3.4 / pxPerUnit) * cityData.scale;
      for (const dot of cityGroup.children) dot.setAttribute('r', r);
    }
  }

  // is this press within the country whose provinces are open?
  function insideDetail(e) {
    const shape = detail && els[detail.code] && els[detail.code].shape;
    if (!shape || !shape.isPointInFill) return true; // no way to tell: leave it alone
    // through the shape's own matrix, so the zoom and the layer's scale are both in it
    const ctm = shape.getScreenCTM();
    if (!ctm) return true;
    const pt = map.createSVGPoint();
    pt.x = e.clientX;
    pt.y = e.clientY;
    return shape.isPointInFill(pt.matrixTransform(ctm.inverse()));
  }

  function svgPoint(evt) {
    const ctm = map.getScreenCTM();
    if (!ctm) return { x: 0, y: 0 };
    const inv = ctm.inverse();
    return { x: evt.clientX * inv.a + evt.clientY * inv.c + inv.e, y: evt.clientX * inv.b + evt.clientY * inv.d + inv.f };
  }

  function zoomAt(px, py, factor) {
    const k = Math.min(maxZoom(), Math.max(1, view.k * factor));
    if (k === view.k) return;
    view.x = px - ((px - view.x) * k) / view.k;
    view.y = py - ((py - view.y) * k) / view.k;
    view.k = k;
    applyView();
  }

  function initZoom() {
    mapwrap.addEventListener(
      'wheel',
      (e) => {
        e.preventDefault();
        const p = svgPoint(e);
        zoomAt(p.x, p.y, Math.exp(-e.deltaY * (e.deltaMode === 1 ? 0.05 : 0.002)));
      },
      { passive: false }
    );

    map.addEventListener('pointerdown', (e) => {
      pointers.set(e.pointerId, e);
      dragged = 0;
      // Remember what was under the finger/cursor: the toggle happens on pointerup,
      // because capturing the pointer for panning would retarget a later click event.
      pressCity = pointers.size === 1 ? (e.target.dataset && +e.target.dataset.city) || null : null;
      pressSub = pointers.size === 1 ? subAt(e) : null;
      pressCode = pointers.size === 1 && !pressSub && grain !== 'sub' ? codeAt(e.target, e.clientX, e.clientY) : null;
      previewed = false;
      clearTimeout(pressTimer);
      if (pressCode || pressSub || pressCity) {
        pressTimer = setTimeout(() => {
          previewed = true;
          if (pressCity) flashCity(pressCity);
          else if (pressSub) flashSub(pressSub);
          else flash(pressCode);
          if (navigator.vibrate) navigator.vibrate(8);
        }, 420);
      }
      if (pointers.size === 2) {
        const [a, b] = [...pointers.values()];
        pinchStart = { dist: Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY), k: view.k };
      }
    });

    map.addEventListener('pointermove', (e) => {
      if (!pointers.has(e.pointerId)) return;
      const prev = pointers.get(e.pointerId);
      pointers.set(e.pointerId, e);

      if (pointers.size === 2 && pinchStart) {
        const [a, b] = [...pointers.values()];
        const dist = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
        const mid = svgPoint({ clientX: (a.clientX + b.clientX) / 2, clientY: (a.clientY + b.clientY) / 2 });
        const target = Math.min(maxZoom(), Math.max(1, (pinchStart.k * dist) / pinchStart.dist));
        zoomAt(mid.x, mid.y, target / view.k);
        dragged = 99;
        return;
      }

      const ctm = map.getScreenCTM();
      if (!ctm) return;
      const sx = (e.clientX - prev.clientX) / ctm.a;
      const sy = (e.clientY - prev.clientY) / ctm.d;
      dragged += Math.abs(e.clientX - prev.clientX) + Math.abs(e.clientY - prev.clientY);
      if (dragged > DRAG_SLOP) clearTimeout(pressTimer);
      if (dragged > DRAG_SLOP && !map.hasPointerCapture(e.pointerId)) {
        map.setPointerCapture(e.pointerId); // only now, so a plain click stays a click
        map.classList.add('dragging');
      }
      view.x += sx;
      view.y += sy;
      applyView();
    });

    const end = (e) => {
      clearTimeout(pressTimer);
      pointers.delete(e.pointerId);
      if (pointers.size < 2) pinchStart = null;
      if (!pointers.size) map.classList.remove('dragging');
      if (e.type === 'pointerup' && dragged <= DRAG_SLOP && !previewed) {
        if (pressCity) toggleCity(pressCity);
        else if (pressSub) toggleSub(pressSub);
        else if (pressCode) toggle(pressCode);
        // inside a country, a press on anything but the country itself is a way out
        else if (detail && !insideDetail(e)) closeDetail();
      }
      pressCode = null;
      pressSub = null;
      pressCity = null;
      previewed = false;
    };
    map.addEventListener('pointerup', end);
    map.addEventListener('pointercancel', end);

    $('zoomIn').onclick = () => (mode === 'globe' ? Globe.zoomBy(1.5) : zoomAt(W / 2, H / 2, 1.6));
    $('zoomOut').onclick = () => (mode === 'globe' ? Globe.zoomBy(1 / 1.5) : zoomAt(W / 2, H / 2, 1 / 1.6));
    $('zoomReset').onclick = () => {
      if (mode === 'globe') return Globe.reset();
      // back to what the view is about: the open country, the chosen continent,
      // or the whole world
      focusBox(detail ? detail.box : activeRegion ? REGION_BOX[activeRegion] : null);
    };
  }

  /* ---------------- interaction ---------------- */
  function onMapHover(e) {
    const cityId = e.target.dataset && e.target.dataset.city;
    if (cityId && cityData) {
      const city = cityData.byId.get(+cityId);
      if (!city) return hideTip();
      const country = byCode.get(city.c);
      const rect = mapwrap.getBoundingClientRect();
      tip.replaceChildren(`${cityName(city)}${country ? `, ${nameOf(country)}` : ''}`);
      tip.hidden = false;
      tip.style.left = `${e.clientX - rect.left}px`;
      tip.style.top = `${e.clientY - rect.top}px`;
      return;
    }
    const sub = subAt(e);
    if (sub && (detail || grain === 'sub')) {
      const unit = unitOf(sub);
      if (!unit) return hideTip();
      const country = !detail && byCode.get(subOwner.get(sub));
      const rect = mapwrap.getBoundingClientRect();
      // outside a country the province needs saying which country it is in
      tip.replaceChildren(`${subNameOf(unit)}${country ? `, ${nameOf(country)}` : ''}`);
      tip.hidden = false;
      tip.style.left = `${e.clientX - rect.left}px`;
      tip.style.top = `${e.clientY - rect.top}px`;
      return;
    }
    const code = codeAt(e.target, e.clientX, e.clientY);
    if (!code) return hideTip();
    showTip(code, e.clientX, e.clientY);
  }

  // shared by the flat map and the globe
  function showTip(code, clientX, clientY) {
    const f = byCode.get(code);
    if (!f) return hideTip();
    const rect = mapwrap.getBoundingClientRect();
    tip.replaceChildren(flagNode(f, 'flag tipflag'), nameOf(f));
    if (f.s === 2) {
      const small = document.createElement('small');
      small.textContent = t('territory');
      tip.appendChild(small);
    }
    tip.hidden = false;
    tip.style.left = `${clientX - rect.left}px`;
    tip.style.top = `${clientY - rect.top}px`;
  }

  function hideTip() {
    tip.hidden = true;
  }

  let flashTimer;
  // Touch screens have no hover, so name feedback rides along with the tap.
  function flash(code, state) {
    const f = byCode.get(code);
    if (!f) return;
    const el = $('flash');
    el.replaceChildren();
    const name = document.createElement('b');
    name.textContent = nameOf(f);
    el.append(flagNode(f, 'flag tipflag'), name);
    if (state !== undefined) {
      const tag = document.createElement('span');
      tag.className = state ? `on lv${state}` : 'off';
      tag.textContent = state ? t(LEVELS.find((l) => l.id === state).key) : t('cleared');
      el.appendChild(tag);
    }
    if (hasDetail(code) && !detail) {
      const into = document.createElement('button');
      into.type = 'button';
      into.className = 'flash-into';
      into.textContent = `${ADMIN1_INDEX[code]} ${t('provinces')} ›`;
      into.onclick = () => openDetail(code);
      el.appendChild(into);
    }
    el.hidden = false;
    clearTimeout(flashTimer);
    // the "open provinces" shortcut is a tap target, so it stays long enough to hit
    flashTimer = setTimeout(() => (el.hidden = true), hasDetail(code) && !detail ? 5200 : state === undefined ? 1800 : 1400);
  }

  function toggle(code) {
    if (!byCode.has(code)) return;
    // painting a country with the level it already has clears it
    const next = marks.get(code) === brush ? 0 : brush;
    if (next) marks.set(code, next);
    else marks.delete(code);
    paintShape(code);
    paintRow(code);
    flash(code, next);
    redrawGlobe();
    updateScore();
    updateHeads();
    save();
    if (location.hash) history.replaceState(null, '', location.pathname + location.search);
    $('hint').classList.add('gone');
  }

  function paintRow(code) {
    const row = els[code]?.row;
    if (!row) return;
    const lv = marks.get(code) || 0;
    row.classList.toggle('on', lv > 0);
    for (const l of LEVELS) row.classList.toggle(`lv${l.id}`, lv === l.id);
    row.setAttribute('aria-pressed', String(lv > 0));
  }

  /* ---------------- list ---------------- */
  // A tap fires the enter event and never the leave one, so the outline used to
  // stay on the map for good — a green border stuck around whatever you last
  // touched. Only a real cursor gets a highlight, and a stale one is cleared
  // whenever the list is rebuilt.
  function clearHighlights() {
    for (const el of map.querySelectorAll('.hl')) el.classList.remove('hl');
  }
  function highlight(targets, on, e) {
    if (on && e && e.pointerType && e.pointerType !== 'mouse') return;
    for (const el of targets) if (el) el.classList.toggle('hl', on);
  }

  function buildList() {
    clearHighlights();
    if (detail) return buildDetailList();
    if (grain === 'sub') return buildCityList();
    const frag = document.createDocumentFragment();
    const sorted = [...FEATURES].sort((a, b) => nameOf(a).localeCompare(nameOf(b), lang));
    for (const f of sorted) {
      const row = document.createElement('button');
      row.type = 'button';
      row.className = 'row';
      row.dataset.code = f.c;
      row.innerHTML =
        `<span class="box"></span><span class="flag"></span>` +
        `<span class="nm"></span>${f.s === 2 ? `<span class="tag"></span>` : ''}` +
        `${hasDetail(f.c) ? '<span class="into" role="button" tabindex="0">›</span>' : ''}`;
      row.querySelector('.flag').replaceWith(flagNode(f));
      row.querySelector('.nm').textContent = nameOf(f);
      if (f.s === 2) row.querySelector('.tag').textContent = t('territory');
      row.onclick = (e) => {
        // the chevron opens the country instead of marking it
        if (e.target.classList.contains('into')) {
          e.stopPropagation();
          openDetail(f.c);
          return;
        }
        toggle(f.c);
      };
      row.onpointerenter = (e) => highlight(shapesOf(f.c), true, e);
      row.onpointerleave = () => highlight(shapesOf(f.c), false);
      els[f.c] = Object.assign(els[f.c] || {}, { row });
      paintRow(f.c);
      frag.appendChild(row);
    }
    const headSel = document.createElement('div');
    headSel.className = 'lhead sel';
    headSel.id = 'headSel';
    const headRest = document.createElement('div');
    headRest.className = 'lhead';
    headRest.id = 'headRest';
    list.replaceChildren(headSel, frag, headRest);
    filterList($('search').value);
  }

  // the same row UI, listing the open country's provinces instead of the world
  // In the city view the list is about provinces: the ones you have marked, and
  // whatever the search box turns up beneath them.
  function buildCityList() {
    const needle = fold($('search').value.trim());
    const frag = document.createDocumentFragment();
    const marked = [...subMarks.keys()].map(unitOf).filter(Boolean);
    marked.sort((a, b) => subNameOf(a).localeCompare(subNameOf(b), lang));
    let shown = 0;
    for (const unit of marked) {
      const country = byCode.get(subOwner.get(unit.c));
      if (needle && !fold(`${subNameOf(unit)} ${unit.n} ${country ? nameOf(country) : ''}`).includes(needle)) continue;
      frag.appendChild(subRow(unit));
      shown++;
    }
    list.replaceChildren(frag);
    showEmpty(!shown);
    showSubMatches(needle);
  }

  const SUB_MATCHES = 40;
  // the same search box finds any province in the world, in any of our languages
  function showSubMatches(needle) {
    for (const row of list.querySelectorAll('.lhead.city-row, .row.city-row.found')) row.remove();
    if (!worldSubs || needle.length < 2) return;
    const hits = [];
    for (const [country, units] of Object.entries(worldSubs.u)) {
      for (const unit of units) {
        if (subMarks.has(unit.c)) continue; // already listed above
        const at = fold(`${subNameOf(unit)}\u0000${unit.n}`).indexOf(needle);
        if (at >= 0) hits.push({ unit, country, rank: at === 0 ? 0 : 1 });
      }
    }
    if (!hits.length) return;
    hits.sort((a, b) => a.rank - b.rank || b.unit.a - a.unit.a);

    const head = document.createElement('div');
    head.className = 'lhead city-row';
    head.textContent = t('provinces');
    const frag = document.createDocumentFragment();
    frag.appendChild(head);
    for (const hit of hits.slice(0, SUB_MATCHES)) frag.appendChild(subRow(hit.unit, true));
    list.appendChild(frag);
    showEmpty(false);
  }

  function subRow(unit, found) {
    const country = byCode.get(subOwner.get(unit.c));
    const row = document.createElement('button');
    row.type = 'button';
    row.className = found ? 'row city-row found' : 'row city-row';
    row.dataset.code = unit.c;
    const lv = subMarks.get(unit.c) || 0;
    row.classList.toggle('on', lv > 0);
    if (lv) row.classList.add(`lv${lv}`);
    row.setAttribute('aria-pressed', String(lv > 0));
    row.innerHTML = '<span class="box"></span><span class="flag"></span><span class="nm"></span>';
    row.querySelector('.flag').replaceWith(country ? flagNode(country) : document.createElement('span'));
    row.querySelector('.nm').textContent = `${subNameOf(unit)}${country ? `, ${nameOf(country)}` : ''}`;
    row.onclick = () => toggleSub(unit.c);
    row.onpointerenter = (e) => highlight(subPaths.get(unit.c) || [], true, e);
    row.onpointerleave = () => highlight(subPaths.get(unit.c) || [], false);
    els[unit.c] = Object.assign(els[unit.c] || {}, { row });
    return row;
  }

  function cityRow(city, found) {
    const country = byCode.get(city.c);
    const row = document.createElement('button');
    row.type = 'button';
    row.className = found ? 'row city-row found' : 'row city-row';
    row.dataset.code = `c${city.i}`;
    const lv = cityMarks.get(city.i) || 0;
    row.classList.toggle('on', lv > 0);
    if (lv) row.classList.add(`lv${lv}`);
    row.setAttribute('aria-pressed', String(lv > 0));
    row.innerHTML = '<span class="box"></span><span class="flag"></span><span class="nm"></span><span class="tag pop"></span>';
    row.querySelector('.flag').replaceWith(country ? flagNode(country) : document.createElement('span'));
    row.querySelector('.nm').textContent = `${cityName(city)}${country ? `, ${nameOf(country)}` : ''}`;
    row.querySelector('.pop').textContent = compact(city.p * 1000);
    row.onclick = () => toggleCity(city.i);
    row.onpointerenter = (e) => highlight([cityGroup && cityGroup.querySelector(`[data-city="${city.i}"]`)], true, e);
    row.onpointerleave = () => highlight([cityGroup && cityGroup.querySelector(`[data-city="${city.i}"]`)], false);
    els[`c${city.i}`] = Object.assign(els[`c${city.i}`] || {}, { row });
    return row;
  }

  function buildDetailList() {
    clearHighlights();
    const frag = document.createDocumentFragment();
    const sorted = [...detail.units].sort((a, b) => subNameOf(a).localeCompare(subNameOf(b), lang));
    for (const unit of sorted) {
      const row = document.createElement('button');
      row.type = 'button';
      row.className = 'row';
      row.dataset.code = unit.c;
      row.innerHTML = '<span class="box"></span><span class="nm"></span>';
      row.querySelector('.nm').textContent = subNameOf(unit);
      row.onclick = () => toggleSub(unit.c);
      row.onpointerenter = (e) => highlight([detail.byId.get(unit.c)?.path], true, e);
      row.onpointerleave = () => highlight([detail.byId.get(unit.c)?.path], false);
      els[unit.c] = Object.assign(els[unit.c] || {}, { row });
      frag.appendChild(row);
      paintSub(unit.c);
    }
    const headSel = document.createElement('div');
    headSel.className = 'lhead sel';
    headSel.id = 'headSel';
    const headRest = document.createElement('div');
    headRest.className = 'lhead';
    headRest.id = 'headRest';
    list.replaceChildren(headSel, frag, headRest);
    filterList($('search').value);
  }

  const indexCache = new Map();
  const searchIndex = (f) => {
    let v = indexCache.get(f.c);
    if (v === undefined) {
      v = fold([f.n, ...Object.values(f.L || {})].join('\u0000'));
      indexCache.set(f.c, v);
    }
    return v;
  };

  const fold = (s) =>
    s
      .toLocaleLowerCase('tr')
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/ı/g, 'i');

  function filterList(q) {
    const needle = fold(q.trim());
    let onShown = 0;
    let offShown = 0;
    // the city view's list is cities: marked ones first, search results under them
    if (grain === 'sub') return buildCityList();
    if (detail) {
      for (const unit of detail.units) {
        const row = els[unit.c] && els[unit.c].row;
        if (!row) continue;
        const hit = !needle || fold([unit.n, ...Object.values(unit.L || {})].join('\u0000')).includes(needle);
        row.hidden = !hit;
        if (hit) (subMarks.has(unit.c) ? onShown++ : offShown++);
      }
      updateHeads(onShown, offShown);
      showEmpty(!onShown && !offShown);
      return;
    }
    for (const f of FEATURES) {
      const row = els[f.c]?.row;
      if (!row) continue;
      // search every language we carry, so "Germany" finds it while the UI is Turkish
      const matchesText = !needle || f.c.toLowerCase() === needle || searchIndex(f).includes(needle);
      const hit = matchesText && (!activeRegion || f.r === activeRegion);
      row.hidden = !hit;
      if (hit) (marks.has(f.c) ? onShown++ : offShown++);
    }
    updateHeads(onShown, offShown);
    showEmpty(!onShown && !offShown && !list.querySelector('.row.city-row:not([hidden])'));
    showCityMatches(needle);
  }

  const CITY_MATCHES = 40; // enough to find what you meant, short enough to scan

  // Cities live in the same list as the countries, but only while searching: a
  // country is a thing you scroll to, a city is a thing you look up.
  async function showCityMatches(needle) {
    // the search owns the heading and its own results — `.found` keeps it from
    // sweeping away the marked cities the city view lists
    for (const row of list.querySelectorAll('.lhead.city-row, .row.city-row.found')) row.remove();
    if (detail || needle.length < 2) return;
    if (mode === 'globe') return;
    const data = await ensureCities();
    await ensureCityNames(lang); // "Roma" and "Rome" both have to work
    if (!data || fold($('search').value.trim()) !== needle) return; // the query moved on

    // "ist" should offer Istanbul before Bristol: names that start with the query
    // come first, then the bigger city
    const hits = [];
    for (const city of data.c) {
      const local = cityName(city);
      let at = fold(local).indexOf(needle);
      if (at !== 0 && local !== city.n) {
        const other = fold(city.n).indexOf(needle);
        if (at < 0 || other === 0) at = other;
      }
      if (at === 0) hits.push({ city, rank: 0 });
      else if (at > 0) hits.push({ city, rank: 1 });
    }
    if (!hits.length) return;
    hits.sort((a, b) => a.rank - b.rank || b.city.p - a.city.p);
    const top = hits.slice(0, CITY_MATCHES).map((h) => h.city);

    const head = document.createElement('div');
    head.className = 'lhead city-row';
    head.textContent = t('cities');
    const frag = document.createDocumentFragment();
    frag.appendChild(head);
    for (const city of top) {
      if (grain === 'sub' && cityMarks.has(city.i)) continue; // already listed above
      frag.appendChild(cityRow(city, true));
    }
    list.appendChild(frag);
    showEmpty(false);
  }

  function showEmpty(nothing) {
    let empty = list.querySelector('.empty');
    if (nothing) {
      if (!empty) {
        empty = document.createElement('p');
        empty.className = 'empty';
        list.appendChild(empty);
      }
      empty.textContent = t('noResults');
      empty.hidden = false;
    } else if (empty) empty.hidden = true;
  }

  // Selected rows float to the top via CSS `order`; these two headers label the groups.
  function updateHeads(onShown, offShown) {
    if (onShown === undefined) {
      onShown = offShown = 0;
      const ids = detail ? detail.units.map((u) => u.c) : FEATURES.map((f) => f.c);
      const held = detail ? subMarks : marks;
      for (const id of ids) {
        const row = els[id]?.row;
        if (!row || row.hidden) continue;
        held.has(id) ? onShown++ : offShown++;
      }
    }
    const sel = $('headSel');
    const rest = $('headRest');
    if (!sel || !rest) return;
    sel.textContent = `${t('headSel')} · ${onShown}`;
    sel.hidden = !onShown;
    rest.textContent = detail ? t('provinces') : t('headRest');
    rest.hidden = !offShown || !onShown;
  }

  /* ---------------- continent filter ---------------- */
  function setRegion(r) {
    activeRegion = activeRegion === r ? null : r;
    for (const f of FEATURES) {
      const off = activeRegion && f.r !== activeRegion;
      for (const s of shapesOf(f.c)) s.classList.toggle('dim', !!off);
    }
    for (const p of map.querySelectorAll('.decor')) p.classList.toggle('dim', !!activeRegion);
    focusBox(activeRegion ? REGION_BOX[activeRegion] : null);
    if (mode === 'globe' && window.Globe && Globe.mounted) {
      if (activeRegion) Globe.spinTo(regionAnchor(activeRegion), 1.35);
      else Globe.reset();
      Globe.render();
    }
    renderRegions();
    filterList($('search').value);
    list.scrollTop = 0;
  }

  function focusBox(box) {
    scene.classList.add('anim');
    if (!box) {
      view.k = 1;
      view.x = view.y = 0;
    } else {
      const [x0, y0, x1, y1] = box;
      const k = Math.min(maxZoom(), Math.max(1, Math.min(W / (x1 - x0), H / (y1 - y0))));
      view.k = k;
      view.x = W / 2 - ((x0 + x1) / 2) * k;
      view.y = H / 2 - ((y0 + y1) / 2) * k;
    }
    applyView();
    clearTimeout(animTimer);
    animTimer = setTimeout(() => scene.classList.remove('anim'), 450);
  }

  /* ---------------- score ---------------- */
  // the markup is the English original, so the labels inside it are translated again
  function restoreWorldSubtitle() {
    if (!worldSubtitle) return;
    const sub = $('scoreSub');
    sub.innerHTML = worldSubtitle;
    for (const el of sub.querySelectorAll('[data-i18n]')) el.textContent = t(el.dataset.i18n);
  }

  function updateScore() {
    if (detail) {
      const done = detailCount();
      const total = detail.units.length;
      $('count').textContent = done;
      $('total').textContent = `/ ${total}`;
      $('pct').textContent = withPct((done / total) * 100);
      $('barfill').style.width = `${(done / total) * 100}%`;
      $('crumbCount').textContent = `${done}/${total}`;
      $('scoreSub').textContent = t('provinces');
      const perLevel = { 1: 0, 2: 0, 3: 0, 4: 0 };
      for (const u of detail.units) {
        const lv = subMarks.get(u.c);
        if (lv) perLevel[lv]++;
      }
      lastCounts = perLevel;
      renderBrush(perLevel);
      return;
    }
    if (grain === 'sub') {
      // the score is about provinces here, and the brush counts them too
      const done = subMarks.size;
      const total = worldSubCount() || done;
      $('count').textContent = done;
      $('total').textContent = `/ ${total}`;
      $('pct').textContent = withPct((done / total) * 100);
      $('barfill').style.width = `${Math.min(100, (done / total) * 100)}%`;
      $('scoreSub').textContent = `${t('provinces')} · ${t('citiesIn').replace('{n}', subCountries())}`;
      const perLevel = { 1: 0, 2: 0, 3: 0, 4: 0 };
      for (const lv of subMarks.values()) perLevel[lv]++;
      lastCounts = perLevel;
      renderBrush(perLevel);
      return;
    }
    restoreWorldSubtitle(); // the city view and the province view write over it
    const s = stats();
    $('count').textContent = s.sov;
    $('cityCount').textContent = cityCount();
    $('cityStat').hidden = !cityCount();
    $('total').textContent = `/ ${SOVEREIGN_TOTAL}`;
    $('terr').textContent = s.terr;
    $('pct').textContent = withPct(s.pct);
    $('barfill').style.width = `${(s.sov / SOVEREIGN_TOTAL) * 100}%`;

    $('landPct').textContent = withPct(s.landPct);
    $('landBar').style.width = `${s.landPct}%`;
    $('landAbs').textContent = `${compact(s.land)} km²`;
    $('popPct').textContent = withPct(s.popPct);
    $('popBar').style.width = `${s.popPct}%`;
    $('popAbs').textContent = `${compact(s.people)} ${t('peopleUnit')}`;

    regionCounts = s.per;
    lastCounts = s.byLevel;
    renderBrush(s.byLevel);
    renderRegions();
  }

  function renderBrush(counts) {
    $('brush').replaceChildren(
      ...LEVELS.map((l) => {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = `lvchip lv${l.id}`;
        b.classList.toggle('on', brush === l.id);
        b.setAttribute('aria-pressed', String(brush === l.id));
        const dot = document.createElement('i');
        const name = document.createElement('b');
        name.textContent = t(l.key);
        const n = document.createElement('span');
        n.textContent = counts ? counts[l.id] || 0 : 0;
        b.append(dot, name, n);
        b.onclick = () => {
          brush = l.id;
          renderBrush(lastCounts);
        };
        return b;
      })
    );
  }

  function renderRegions() {
    const chips = REGIONS.map((r) => {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'region';
      btn.classList.toggle('on', activeRegion === r);
      btn.setAttribute('aria-pressed', String(activeRegion === r));
      const b = document.createElement('b');
      b.textContent = REGION_NAMES[lang][r];
      const s = document.createElement('span');
      s.textContent = `${regionCounts[r] || 0}/${REGION_TOTAL[r]}`;
      btn.append(b, s);
      btn.onclick = () => setRegion(r);
      return btn;
    });

    const all = document.createElement('button');
    all.type = 'button';
    all.className = 'region all';
    all.classList.toggle('on', !activeRegion);
    all.setAttribute('aria-pressed', String(!activeRegion));
    const ab = document.createElement('b');
    ab.textContent = t('allRegions');
    const as = document.createElement('span');
    as.textContent = `${$('count').textContent}/${SOVEREIGN_TOTAL}`;
    all.append(ab, as);
    all.onclick = () => activeRegion && setRegion(activeRegion);
    chips.push(all);

    $('regions').replaceChildren(...chips);
  }

  /* ---------------- provinces ---------------- */
  const hasDetail = (code) => !!(window.ADMIN1_INDEX && ADMIN1_INDEX[code]);
  // unit order per country, for the share link — filled as detail files load
  // The world layer and the per-country files hold the same units in the same order,
  // so either can number them for the link; whichever is loaded wins.
  const unitOrder = () => {
    const order = {};
    for (const [c, list] of Object.entries((window.ADMIN1_WORLD && ADMIN1_WORLD.u) || {})) {
      order[c] = list.map((u) => u.c);
    }
    for (const [c, d] of Object.entries(window.ADMIN1 || {})) order[c] = d.u.map((u) => u.c);
    return order;
  };
  const detailFiles = {};

  function loadDetail(code) {
    if (window.ADMIN1 && ADMIN1[code]) return Promise.resolve(ADMIN1[code]);
    if (!detailFiles[code]) {
      detailFiles[code] = loadScript(`js/admin1/${code}.js?${ASSET_V}`)
        .then(() => ADMIN1[code])
        .catch(() => {
          delete detailFiles[code];
          return null;
        });
    }
    return detailFiles[code];
  }

  async function openDetail(code) {
    if (!hasDetail(code)) return;
    // the province layer of one country is drawn on the flat map
    if (mode !== 'map') await setView('map');
    const data = await loadDetail(code);
    if (!data) return toast(t('copyFail'));

    // The province layer is 1:10m and the world map 1:50m, so their coastlines
    // disagree. Clipping the provinces to the country's own world-map shape makes
    // the two agree exactly: the outer <g> carries the clip, the inner one the
    // scale, because a transform on the clipped element moves its clip too.
    const clip = document.createElementNS(SVG_NS, 'clipPath');
    clip.id = 'detailClip';
    const clipShape = document.createElementNS(SVG_NS, 'path');
    // the scale goes on the shape itself: a <g> inside a clipPath is ignored, which
    // silently leaves the clip empty and hides everything it should have kept
    clipShape.setAttribute('transform', `scale(${1 / PATH_SCALE})`);
    clipShape.setAttribute('d', byCode.get(code).d || '');
    clip.appendChild(clipShape);

    // the definition lives outside the group it clips — a clipPath nested inside its
    // own target reads as a circular reference and Chrome clips everything away
    let defs = map.querySelector('defs');
    if (!defs) {
      defs = document.createElementNS(SVG_NS, 'defs');
      map.insertBefore(defs, map.firstChild);
    }
    defs.replaceChildren(clip);

    const group = document.createElementNS(SVG_NS, 'g');
    group.setAttribute('class', 'detail');
    group.setAttribute('clip-path', 'url(#detailClip)');
    const inner = document.createElementNS(SVG_NS, 'g');
    inner.setAttribute('transform', `scale(${1 / data.ps})`);
    group.appendChild(inner);
    const byId = new Map();
    for (const unit of data.u) {
      const path = document.createElementNS(SVG_NS, 'path');
      path.setAttribute('d', unit.d);
      path.setAttribute('class', 'sub');
      path.dataset.sub = unit.c;
      inner.appendChild(path);
      register(unit.c, path);
      byId.set(unit.c, { unit, path });
    }
    scene.appendChild(group);

    $('search').value = ''; // a country search would hide every province
    $('search').placeholder = t('searchSub');
    detail = { code, units: data.u, byId, box: data.box, group };
    for (const id of byId.keys()) paintSub(id);
    document.body.classList.add('in-detail');
    $('crumbs').hidden = false;
    $('crumbName').textContent = nameOf(byCode.get(code));
    dimForDetail();
    focusBox(data.box);
    buildList();
    updateScore();
  }

  function closeDetail() {
    if (!detail) return;
    for (const { path } of detail.byId.values()) unregister(path);
    detail.group.remove();
    map.querySelector('defs')?.replaceChildren(); // the clip belonged to that country
    detail = null;
    $('search').value = '';
    $('search').placeholder = t('search');
    restoreWorldSubtitle();
    document.body.classList.remove('in-detail');
    $('crumbs').hidden = true;
    applyLang(); // the restored subtitle needs its translations back
    dimForDetail();
    focusBox(activeRegion ? REGION_BOX[activeRegion] : null);
    buildList();
    updateScore();
  }

  // while a country is open its neighbours fade back, and the country's own fill
  // steps aside so the provinces on top of it are what you see
  function dimForDetail() {
    for (const f of FEATURES) {
      const off = detail ? f.c !== detail.code : !!activeRegion && f.r !== activeRegion;
      for (const el of shapesOf(f.c)) {
        el.classList.toggle('dim', !!off);
        el.classList.toggle('under', !!detail && f.c === detail.code);
      }
    }
  }

  function paintSub(id) {
    const lv = subMarks.get(id) || 0;
    for (const path of subPaths.get(id) || []) {
      path.classList.toggle('on', lv > 0);
      for (const l of LEVELS) path.classList.toggle(`lv${l.id}`, lv === l.id);
      // Chrome does not repaint a clipped group when only a fill inside it changes —
      // the colour would appear the next time you panned. Moving the path to the end
      // of its group invalidates it, and puts the one you marked over its neighbours'
      // borders while it is at it.
      if (path.parentNode) path.parentNode.appendChild(path);
    }
    const row = els[id] && els[id].row;
    if (row) {
      row.classList.toggle('on', lv > 0);
      for (const l of LEVELS) row.classList.toggle(`lv${l.id}`, lv === l.id);
      row.setAttribute('aria-pressed', String(lv > 0));
    }
  }

  function toggleSub(id) {
    if (!unitOf(id)) return;
    const next = subMarks.get(id) === brush ? 0 : brush;
    if (next) subMarks.set(id, next);
    else subMarks.delete(id);
    paintSub(id);
    flashSub(id, next);
    if (grain === 'sub') buildList();
    updateScore();
    updateHeads();
    save();
    $('hint').classList.add('gone');
  }

  function flashSub(id, state) {
    const unit = unitOf(id);
    if (!unit) return;
    const el = $('flash');
    const name = document.createElement('b');
    name.textContent = subNameOf(unit);
    const country = byCode.get(subOwner.get(id) || (detail && detail.code));
    el.replaceChildren(name);
    if (country && !detail) el.prepend(flagNode(country, 'flag tipflag'));
    if (state !== undefined) {
      const tag = document.createElement('span');
      tag.className = state ? `on lv${state}` : 'off';
      tag.textContent = state ? t(LEVELS.find((l) => l.id === state).key) : t('cleared');
      el.appendChild(tag);
    }
    el.hidden = false;
    clearTimeout(flashTimer);
    flashTimer = setTimeout(() => (el.hidden = true), 1400);
  }


  const subNameOf = (unit) =>
    (unit.at !== undefined && !unit.L ? worldSubName(unit) : null) || (unit.L && unit.L[lang]) || unit.n;
  const detailCount = () => (detail ? detail.units.filter((u) => subMarks.has(u.c)).length : 0);

  /* ---------------- cities ---------------- */
  // Cities are not a mode of their own any more: the ones you have marked are drawn
  // on the world map as coloured dots, so a country is not painted whole just
  // because you saw one of its cities. The dataset loads the first time it is
  // needed — a search, a link, or marks restored from storage.
  let cityData = null;
  let cityLoading = null;
  let cityGroup = null;

  // GeoNames names cities in English or in their own language, so a Turkish
  // visitor typing "Roma" would never find Rome. The names for one language are a
  // few kilobytes; all twelve would be 150, so each is a file of its own and only
  // the one in use is fetched.
  const cityNamePacks = new Map();
  function ensureCityNames(lang) {
    if (lang === 'en') return Promise.resolve(null);
    if (!cityNamePacks.has(lang)) {
      cityNamePacks.set(
        lang,
        loadScript(`js/cities/${lang}.js?${ASSET_V}`)
          .then(() => (window.CITY_NAMES || {})[lang] || null)
          .catch(() => null)
      );
    }
    return cityNamePacks.get(lang);
  }

  // the name to show and to search: the visitor's language when we have it
  function cityName(city) {
    const pack = (window.CITY_NAMES || {})[lang];
    return (pack && pack[city.ix]) || city.n;
  }

  function ensureCities() {
    if (cityData) return Promise.resolve(cityData);
    if (!cityLoading) {
      cityLoading = loadScript(`js/cities.js?${ASSET_V}`)
        .then(() => ensureCityNames(lang))
        .then(() => {
          cityData = window.CITIES;
          cityData.c.forEach((c, i) => (c.ix = i)); // the name packs are keyed by position
          cityData.byId = new Map(cityData.c.map((c) => [c.i, c]));
          return cityData;
        })
        .catch(() => {
          cityLoading = null;
          return null;
        });
    }
    return cityLoading;
  }

  async function applyPendingCities() {
    if (!pendingCities) return;
    const data = await ensureCities();
    if (!data) return;
    const list = Share.decodeCities(cityOrder(), pendingCities);
    pendingCities = null;
    if (!list || !list.length) return;
    cityMarks.clear();
    for (const [id, lv] of list) cityMarks.set(id, lv);
    save();
    drawCities();
    updateScore();
  }

  // only the marked ones are ever in the DOM, which is what keeps this cheap
  function drawCities() {
    if (!cityGroup) {
      cityGroup = document.createElementNS(SVG_NS, 'g');
      cityGroup.setAttribute('id', 'citymarks');
      scene.appendChild(cityGroup);
    }
    if (!cityData) return;
    cityGroup.setAttribute('transform', `scale(${1 / cityData.scale})`);
    cityGroup.replaceChildren();
    for (const [id, lv] of cityMarks) {
      const city = cityData.byId.get(id);
      if (!city) continue;
      const dot = document.createElementNS(SVG_NS, 'circle');
      dot.setAttribute('cx', city.x);
      dot.setAttribute('cy', city.y);
      dot.setAttribute('class', `city on lv${lv}`);
      dot.dataset.city = id;
      cityGroup.appendChild(dot);
    }
    sizeMarkers();
  }

  /* ---------------- the city view: the world by its provinces ---------------- */
  // Natural Earth's admin-1 units — Türkiye's 81 provinces, the 50 US states, and so
  // on for every country — drawn straight onto the world map so each one can be
  // marked on its own. They are the same units, in the same order, as the per-country
  // files a country's detail view loads, so a province marked here is the same
  // province there and travels in the same &p= link.
  let worldSubs = null;
  let worldSubsLoading = null;
  let subGroup = null;
  const subPaths = new Map(); // unit code -> the paths drawing it, in either layer
  const subOwner = new Map(); // unit code -> its country

  function ensureWorldSubs() {
    if (worldSubs) return Promise.resolve(worldSubs);
    if (!worldSubsLoading) {
      worldSubsLoading = Promise.all([
        loadScript(`js/admin1/world.js?${ASSET_V}`),
        ensureSubNames(lang),
      ])
        .then(() => {
          worldSubs = window.ADMIN1_WORLD || null;
          if (worldSubs) {
            for (const [code, list] of Object.entries(worldSubs.u)) {
              list.forEach((unit, i) => {
                unit.at = i; // the name packs are keyed by position
                subOwner.set(unit.c, code);
              });
            }
          }
          return worldSubs;
        })
        .catch(() => {
          worldSubsLoading = null;
          return null;
        });
    }
    return worldSubsLoading;
  }

  // one small file per language, like the city names: nobody downloads eleven
  const subNamePacks = new Map();
  function ensureSubNames(which) {
    if (which === 'en') return Promise.resolve(null);
    if (!subNamePacks.has(which)) {
      subNamePacks.set(
        which,
        loadScript(`js/admin1/names/${which}.js?${ASSET_V}`)
          .then(() => (window.SUB_NAMES || {})[which] || null)
          .catch(() => null)
      );
    }
    return subNamePacks.get(which);
  }

  // the detail layer carries its own translations; the world layer looks them up
  function worldSubName(unit) {
    const pack = (window.SUB_NAMES || {})[lang];
    const country = subOwner.get(unit.c);
    const named = pack && country && pack[country] && pack[country][unit.at];
    return named || unit.n;
  }

  // A province is clipped to its own country's outline, exactly like the detail
  // layer: the two are drawn from different sources and would otherwise disagree
  // along the coast.
  function buildSubLayer() {
    if (!worldSubs || subGroup) return;
    let defs = map.querySelector('defs#subdefs');
    if (!defs) {
      defs = document.createElementNS(SVG_NS, 'defs');
      defs.id = 'subdefs';
      map.insertBefore(defs, map.firstChild);
    }
    subGroup = document.createElementNS(SVG_NS, 'g');
    subGroup.setAttribute('id', 'worldsubs');

    const frag = document.createDocumentFragment();
    const clips = document.createDocumentFragment();
    for (const [code, list] of Object.entries(worldSubs.u)) {
      const feature = byCode.get(code);
      if (!feature || !feature.d) continue;

      const clip = document.createElementNS(SVG_NS, 'clipPath');
      clip.id = `subclip-${code}`;
      const shape = document.createElementNS(SVG_NS, 'path');
      shape.setAttribute('transform', `scale(${1 / PATH_SCALE})`);
      shape.setAttribute('d', feature.d);
      clip.appendChild(shape);
      clips.appendChild(clip);

      const outer = document.createElementNS(SVG_NS, 'g');
      outer.setAttribute('clip-path', `url(#subclip-${code})`);
      const inner = document.createElementNS(SVG_NS, 'g');
      inner.setAttribute('transform', `scale(${1 / worldSubs.ps})`);
      for (const unit of list) {
        const path = document.createElementNS(SVG_NS, 'path');
        path.setAttribute('d', unit.d);
        path.setAttribute('class', 'sub world');
        path.dataset.sub = unit.c;
        inner.appendChild(path);
        register(unit.c, path);
      }
      outer.appendChild(inner);
      frag.appendChild(outer);
    }
    defs.replaceChildren(clips);
    subGroup.appendChild(frag);
    scene.insertBefore(subGroup, scene.querySelector('#dots'));
    for (const code of subMarks.keys()) paintSub(code);
  }

  // The globe wants lon/lat, and the province data is in map coordinates — but the
  // map's projection is invertible, so the same file serves both views and nothing
  // extra is downloaded for the globe.
  let globeSubs = null;
  let globeSubsLoading = null;

  function decodePath(d, ps) {
    const rings = [];
    let ring = null;
    let x = 0;
    let y = 0;
    const tokens = d.match(/[MmlZ]|-?\d+/g) || [];
    let mode = '';
    for (let i = 0; i < tokens.length; i++) {
      const token = tokens[i];
      if (token === 'Z') {
        ring = null;
        continue;
      }
      if (/[MmlZ]/.test(token)) {
        mode = token;
        if (token === 'M' || token === 'm') {
          const dx = +tokens[++i];
          const dy = +tokens[++i];
          x = token === 'M' ? dx : x + dx;
          y = token === 'M' ? dy : y + dy;
          ring = [[x / ps, y / ps]];
          rings.push(ring);
        }
        continue;
      }
      // a bare number pair continues the current line
      const dx = +token;
      const dy = +tokens[++i];
      x += dx;
      y += dy;
      if (ring) ring.push([x / ps, y / ps]);
      void mode;
    }
    return rings.filter((r) => r.length > 2);
  }

  // Inverting a million points through d3's Natural Earth solver takes seconds. The
  // projection is separable — y depends only on latitude, x is longitude times a
  // factor that depends only on latitude — so one table of 1,800 latitudes turns
  // every inversion into a lookup and a division.
  function inverter() {
    const proj = d3.geoNaturalEarth1().precision(0.1);
    proj.fitWidth(1000, { type: 'Sphere' });
    const top = proj([0, 90])[1];
    proj.translate([proj.translate()[0], proj.translate()[1] - top]);

    const STEPS = 1800;
    const ys = new Float64Array(STEPS + 1);
    const x0 = new Float64Array(STEPS + 1);
    const dx = new Float64Array(STEPS + 1);
    for (let i = 0; i <= STEPS; i++) {
      const lat = 90 - (180 * i) / STEPS; // y grows downwards, so latitude descends
      const a = proj([0, lat]);
      const b = proj([1, lat]);
      ys[i] = a[1];
      x0[i] = a[0];
      dx[i] = b[0] - a[0];
    }

    return ([x, y]) => {
      if (!(y >= ys[0]) || y > ys[STEPS]) return null;
      let lo = 0;
      let hi = STEPS;
      while (hi - lo > 1) {
        const mid = (lo + hi) >> 1;
        if (ys[mid] <= y) lo = mid;
        else hi = mid;
      }
      const span = ys[hi] - ys[lo] || 1;
      const f = (y - ys[lo]) / span;
      const lat = 90 - (180 * (lo + f)) / STEPS;
      const width = dx[lo] + (dx[hi] - dx[lo]) * f;
      const left = x0[lo] + (x0[hi] - x0[lo]) * f;
      if (!width) return null;
      const lon = (x - left) / width;
      return lon >= -181 && lon <= 181 ? [lon, lat] : null;
    };
  }

  function ensureGlobeSubs() {
    if (globeSubs) return Promise.resolve(globeSubs);
    if (!globeSubsLoading) {
      globeSubsLoading = Promise.all([ensureGlobe(), ensureWorldSubs()])
        .then(([globeReady, data]) => {
          if (!globeReady || !data) return null;
          const invert = inverter();
          const out = [];
          for (const [country, list] of Object.entries(data.u)) {
            for (const unit of list) {
              const polygons = [];
              for (const ring of decodePath(unit.d, data.ps)) {
                const ll = [];
                for (const point of ring) {
                  const at = invert(point);
                  if (at) ll.push(at);
                }
                if (ll.length > 2) {
                  ll.push(ll[0]);
                  polygons.push([ll]);
                }
              }
              if (!polygons.length) continue;
              out.push({
                code: unit.c,
                country,
                feature: { type: 'Feature', geometry: { type: 'MultiPolygon', coordinates: polygons } },
              });
            }
          }
          globeSubs = out;
          Globe.setSubs(out);
          return out;
        })
        .catch(() => {
          globeSubsLoading = null;
          return null;
        });
    }
    return globeSubsLoading;
  }

  function register(code, path) {
    const list = subPaths.get(code);
    if (list) list.push(path);
    else subPaths.set(code, [path]);
  }

  function unregister(path) {
    for (const [code, list] of subPaths) {
      const at = list.indexOf(path);
      if (at >= 0) list.splice(at, 1);
      if (!list.length) subPaths.delete(code);
    }
  }

  // the unit behind a code, wherever it is loaded from
  function unitOf(code) {
    if (detail && detail.byId.has(code)) return detail.byId.get(code).unit;
    const country = subOwner.get(code);
    return (worldSubs && country && worldSubs.u[country].find((u) => u.c === code)) || null;
  }

  const subCountries = () => {
    const codes = new Set();
    for (const code of subMarks.keys()) {
      const country = subOwner.get(code) || (detail && detail.code);
      if (country) codes.add(country);
    }
    return codes.size;
  };

  const worldSubCount = () =>
    worldSubs ? Object.values(worldSubs.u).reduce((n, list) => n + list.length, 0) : subMarks.size;

  async function toggleCity(id) {
    const data = await ensureCities();
    if (!data || !data.byId.has(id)) return;
    const next = cityMarks.get(id) === brush ? 0 : brush;
    if (next) cityMarks.set(id, next);
    else cityMarks.delete(id);
    drawCities();
    flashCity(id, next);
    if (grain === 'sub') buildList(); // the city view lists what you have marked
    const row = els[`c${id}`] && els[`c${id}`].row;
    if (row) {
      row.classList.toggle('on', next > 0);
      for (const l of LEVELS) row.classList.toggle(`lv${l.id}`, next === l.id);
      row.setAttribute('aria-pressed', String(next > 0));
    }
    updateScore();
    save();
    $('hint').classList.add('gone');
  }

  function flashCity(id, state) {
    const city = cityData && cityData.byId.get(id);
    if (!city) return;
    const el = $('flash');
    const country = byCode.get(city.c);
    const name = document.createElement('b');
    name.textContent = `${cityName(city)}${country ? `, ${nameOf(country)}` : ''}`;
    el.replaceChildren(name);
    if (country) el.prepend(flagNode(country, 'flag tipflag'));
    if (state !== undefined) {
      const tag = document.createElement('span');
      tag.className = state ? `on lv${state}` : 'off';
      tag.textContent = state ? t(LEVELS.find((l) => l.id === state).key) : t('cleared');
      el.appendChild(tag);
    }
    el.hidden = false;
    clearTimeout(flashTimer);
    flashTimer = setTimeout(() => (el.hidden = true), 1400);
  }

  const cityCount = () => cityMarks.size;
  const cityOrder = () => (cityData ? cityData.c.map((c) => c.i) : window.CITIES ? CITIES.c.map((c) => c.i) : []);

  /* ---------------- globe ---------------- */
  // ?v= keeps a cached stylesheet from ever pairing with a newer script; bump it
  // in index.html and here together when deploying
  const ASSET_V = 'v=17';
  const GLOBE_FILES = [
    'js/vendor/d3-array-shim.js',
    'js/vendor/d3-geo.min.js',
    `js/globe-data.js?${ASSET_V}`,
    `js/globe.js?${ASSET_V}`,
  ];

  function loadScript(src) {
    return new Promise((resolve, reject) => {
      const el = document.createElement('script');
      el.src = src;
      el.onload = resolve;
      el.onerror = () => reject(new Error(src));
      document.head.appendChild(el);
    });
  }

  // ~310 KB of geometry and d3-geo, fetched the first time someone asks for the
  // globe. Everyone who asks while it is in flight waits on the same promise
  // instead of being told "no".
  async function ensureGlobe() {
    if (window.Globe && window.GLOBE_DATA) return true;
    if (!globeLoading) {
      toast(t('loading'));
      globeLoading = (async () => {
        for (const src of GLOBE_FILES) await loadScript(src);
        return true;
      })().catch(() => {
        globeLoading = null;
        toast(t('copyFail'));
        return false;
      });
    }
    return globeLoading;
  }

  function globeOptions() {
    return {
      colorOf: (code) => (marks.has(code) ? cssVar(`--lv${marks.get(code)}`) : null),
      dimmed: (code) => !!activeRegion && byCode.get(code)?.r !== activeRegion,
      isMarked: (code) => marks.has(code),
      markerCodes: FEATURES.filter((f) => f.a < DOT_AREA).map((f) => f.c),
      palette: () => ({
        ocean: cssVar('--ocean'),
        land: cssVar('--land'),
        border: cssVar('--border'),
        line: cssVar('--line'),
      }),
      grain: () => grain,
      subColor: (code) => (subMarks.has(code) ? cssVar(`--lv${subMarks.get(code)}`) : null),
      onPickSub: (code) => toggleSub(code),
      onPick: (code) => toggle(code),
      onHover: (code, e) => {
        if (!code || !e) return hideTip();
        showTip(code, e.clientX, e.clientY);
      },
      onHoverSub: (code, e) => {
        const unit = code && unitOf(code);
        if (!unit || !e) return hideTip();
        const country = byCode.get(subOwner.get(code));
        const rect = mapwrap.getBoundingClientRect();
        tip.replaceChildren(`${subNameOf(unit)}${country ? `, ${nameOf(country)}` : ''}`);
        tip.hidden = false;
        tip.style.left = `${e.clientX - rect.left}px`;
        tip.style.top = `${e.clientY - rect.top}px`;
      },
    };
  }

  async function setView(next) {
    if (next === 'globe' && !(await ensureGlobe())) return;
    mode = next;
    savePrefs();
    applyViewState();
    if (mode === 'globe') {
      if (!Globe.mounted) Globe.mount($('globe'), globeOptions());
      Globe.resize();
      if (activeRegion) Globe.spinTo(regionAnchor(activeRegion), 1.35);
      if (grain === 'sub') ensureGlobeSubs();
    }
  }

  // Countries or the provinces inside them — the same choice in either view.
  async function setGrain(next) {
    if (next === grain) return;
    if (next === 'sub') {
      if (detail) closeDetail(); // one country's provinces, or the whole world's
      toast(t('loadingCities'));
      if (!(await ensureWorldSubs())) return toast(t('copyFail'));
      buildSubLayer();
      if (mode === 'globe') await ensureGlobeSubs();
    }
    grain = next;
    savePrefs();
    applyViewState();
  }

  // everything both switches change, in one place
  function applyViewState() {
    const onGlobe = mode === 'globe';
    const onSubs = grain === 'sub';
    document.body.classList.toggle('in-subs', onSubs);
    if (subGroup) subGroup.style.display = onSubs && !onGlobe ? '' : 'none';
    // set display inline as well as the attribute: a stale cached stylesheet without
    // the [hidden] rules would otherwise leave the flat map showing under the globe
    $('map').hidden = onGlobe;
    $('map').style.display = onGlobe ? 'none' : '';
    $('globe').hidden = !onGlobe;
    $('globe').style.display = onGlobe ? '' : 'none';
    $('viewMap').classList.toggle('on', !onGlobe);
    $('viewGlobe').classList.toggle('on', onGlobe);
    $('grainCountry').classList.toggle('on', !onSubs);
    $('grainSub').classList.toggle('on', onSubs);
    $('hint').textContent = hintText();
    hideTip();
    buildList();
    updateScore();
    redrawGlobe();
  }

  const hintText = () =>
    grain === 'sub' ? t('hintCities')
      : mode === 'globe' ? t('hintGlobe')
        : matchMedia('(hover: none)').matches ? t('hintTouch') : t('hint');

  // rough centre of a continent: the marked-or-not country closest to its box centre
  function regionAnchor(region) {
    const box = REGION_BOX[region];
    if (!box) return null;
    const cx = (box[0] + box[2]) / 2;
    const cy = (box[1] + box[3]) / 2;
    let best = null;
    let bestD = Infinity;
    for (const f of FEATURES) {
      if (f.r !== region || !f.a) continue;
      const d = (f.x - cx) ** 2 + (f.y - cy) ** 2;
      if (d < bestD) {
        bestD = d;
        best = f.c;
      }
    }
    return best;
  }

  const redrawGlobe = () => {
    if (mode === 'globe' && window.Globe && Globe.mounted) Globe.render();
  };

  /* ---------------- share card ---------------- */
  const CARD_SIZES = [
    ['link', 'sizeLink'],
    ['square', 'sizeSquare'],
    ['story', 'sizeStory'],
  ];

  function cssVar(name) {
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  }

  function stats() {
    let sov = 0;
    let terr = 0;
    let land = 0;
    let people = 0;
    const per = {};
    const byLevel = { 1: 0, 2: 0, 3: 0, 4: 0 };
    for (const [code, lv] of marks) {
      const f = byCode.get(code);
      if (!f) continue;
      byLevel[lv]++;
      if (!BEEN.has(lv)) continue; // a wish is not a visit
      land += f.k || 0;
      people += f.p || 0;
      if (isCountry(f)) {
        sov++;
        per[f.r] = (per[f.r] || 0) + 1;
      } else terr++;
    }
    return {
      sov,
      terr,
      per,
      byLevel,
      wish: byLevel[4],
      land,
      people,
      total: SOVEREIGN_TOTAL,
      pct: Math.round((sov / SOVEREIGN_TOTAL) * 100),
      landPct: (land / WORLD_LAND) * 100,
      popPct: (people / WORLD_POP) * 100,
    };
  }

  /* ---------------- number formatting ---------------- */
  const compact = (v) =>
    new Intl.NumberFormat(localeOf(), { notation: 'compact', maximumFractionDigits: 1 }).format(v);
  // one decimal below 10% so a single country still registers
  const withPct = (v) =>
    new Intl.NumberFormat(localeOf(), { style: 'percent', maximumFractionDigits: v < 10 ? 1 : 0 }).format(v / 100);

  function shareUrl() {
    const sub = Share.encodeSub(unitOrder(), subMarks);
    const cities = Share.encodeCities(cityOrder(), cityMarks);
    return (
      `${location.origin}${location.pathname}#v2=${encodeShare()}` +
      `${sub ? `&p=${sub}` : ''}${cities ? `&c=${cities}` : ''}`
    );
  }

  function shareMessage() {
    if (grain === 'sub') return t('shareTextSubs').replace('{n}', subMarks.size);
    const s = stats();
    return t('shareText').replace('{n}', s.sov).replace('{total}', s.total).replace('{pct}', withPct(s.pct));
  }

  // The card follows the view: in the city view it is about provinces, so the map
  // paints those, the headline counts them, and the breakdown is by country rather
  // than by continent.
  const shorten = (name, max) => (name.length > max ? `${name.slice(0, max - 1).trimEnd()}…` : name);

  function subCardInput(size) {
    const done = subMarks.size;
    const total = worldSubCount() || done;
    const byLevel = { 1: 0, 2: 0, 3: 0, 4: 0 };
    const perCountry = new Map();
    const shapes = [];
    const names = [];
    for (const [code, lv] of subMarks) {
      byLevel[lv] = (byLevel[lv] || 0) + 1;
      const country = subOwner.get(code);
      if (country) perCountry.set(country, (perCountry.get(country) || 0) + 1);
      const unit = unitOf(code);
      if (!unit) continue;
      names.push(subNameOf(unit));
      const world = worldSubs && country && worldSubs.u[country].find((u) => u.c === code);
      if (world) shapes.push({ d: world.d, lv });
    }
    names.sort((a, b) => a.localeCompare(b, lang));
    const pct = total ? (done / total) * 100 : 0;
    const top = [...perCountry.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([code, have]) => ({
        label: shorten(nameOf(byCode.get(code)) || code, 14),
        have,
        total: (worldSubs && worldSubs.u[code] && worldSubs.u[code].length) || have,
      }));

    return {
      size,
      world: WORLD,
      marks,
      subs: { ps: (worldSubs && worldSubs.ps) || 1, shapes },
      levels: LEVELS.map((l) => ({ id: l.id, label: t(l.key), count: byLevel[l.id] || 0, color: cssVar(`--lv${l.id}`) })),
      stats: { sov: done, total, terr: 0, pct: Math.round(pct) },
      regions: top,
      names,
      extras: [
        { label: t('countries'), value: String(perCountry.size), sub: `${done} ${t('provinces')}`, ratio: perCountry.size / SOVEREIGN_TOTAL },
        ...(cityCount() ? [{ label: t('cities'), value: String(cityCount()), sub: '', ratio: Math.min(1, cityCount() / 40) }] : []),
      ],
      texts: {
        title: t('cardTitleSubs'),
        countries: t('provinces'),
        territories: t('territories'),
        pct: withPct(pct),
        more: t('cardMore'),
        url: (location.host + location.pathname).replace(/\/(index\.html)?$/, ''),
      },
      colors: {
        bg: cssVar('--bg-2'),
        ocean: cssVar('--ocean'),
        land: cssVar('--land'),
        on: cssVar('--lv2'),
        ink: cssVar('--ink'),
        accent: cssVar('--accent'),
      },
    };
  }

  function buildCardSVG(size) {
    if (grain === 'sub') return EarthCard.build(subCardInput(size));
    const s = stats();
    const selected = FEATURES.filter((f) => been(f.c) && isCountry(f))
      .map(nameOf)
      .sort((a, b) => a.localeCompare(b, lang));
    return EarthCard.build({
      size,
      world: WORLD,
      marks,
      levels: LEVELS.map((l) => ({ id: l.id, label: t(l.key), count: s.byLevel[l.id], color: cssVar(`--lv${l.id}`) })),
      stats: s,
      regions: REGIONS.map((r) => ({ label: REGION_NAMES[lang][r], have: s.per[r] || 0, total: REGION_TOTAL[r] })),
      names: selected,
      extras: [
        { label: t('land'), value: withPct(s.landPct), sub: `${compact(s.land)} km²`, ratio: s.landPct / 100 },
        { label: t('people'), value: withPct(s.popPct), sub: `${compact(s.people)} ${t('peopleUnit')}`, ratio: s.popPct / 100 },
      ],
      texts: {
        title: t('cardTitle'),
        countries: t('countries'),
        territories: t('territories'),
        pct: withPct(s.pct),
        more: t('cardMore'),
        url: (location.host + location.pathname).replace(/\/(index\.html)?$/, ''),
      },
      colors: {
        bg: cssVar('--bg-2'),
        ocean: cssVar('--ocean'),
        land: cssVar('--land'),
        on: cssVar('--lv2'),
        ink: cssVar('--ink'),
        accent: cssVar('--accent'),
      },
    });
  }

  function svgToPng(svg, scale = 2) {
    return new Promise((resolve, reject) => {
      const size = svg.match(/width="(\d+)" height="(\d+)"/);
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = (size ? +size[1] : img.width) * scale;
        canvas.height = (size ? +size[2] : img.height) * scale;
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
        canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error('toBlob failed'))), 'image/png');
      };
      img.onerror = () => reject(new Error('svg load failed'));
      img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
    });
  }

  async function renderCard() {
    const svg = buildCardSVG(cardSize);
    $('cardImg').src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
    $('cardImg').alt = shareMessage();
    cardBlob = null;
    try {
      cardBlob = await svgToPng(svg, cardSize === 'link' ? 2 : 1.5);
    } catch {
      cardBlob = null;
    }
    updateShareButtons();
  }

  function canSharePng() {
    if (!navigator.canShare || !cardBlob) return false;
    try {
      return navigator.canShare({ files: [new File([cardBlob], 'earthvisited.png', { type: 'image/png' })] });
    } catch {
      return false;
    }
  }

  function updateShareButtons() {
    $('sysShare').hidden = !canSharePng();
    $('saveImg').disabled = !cardBlob;
    $('copyImg').disabled = !cardBlob || !window.ClipboardItem;
  }

  function renderSizes() {
    $('sizes').replaceChildren(
      ...CARD_SIZES.map(([key, label]) => {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = 'size';
        b.classList.toggle('on', cardSize === key);
        b.setAttribute('aria-pressed', String(cardSize === key));
        b.textContent = t(label);
        b.onclick = () => {
          cardSize = key;
          renderSizes();
          renderCard();
        };
        return b;
      })
    );
  }

  function openShare() {
    history.replaceState(null, '', shareUrl());
    cardSize = cardSize || 'link';
    renderSizes();
    renderCard();
    const sheet = $('sheet');
    if (typeof sheet.showModal === 'function') sheet.showModal();
    else sheet.setAttribute('open', '');
  }

  function saveCard() {
    if (!cardBlob) return;
    const href = URL.createObjectURL(cardBlob);
    const a = document.createElement('a');
    a.href = href;
    a.download = `earthvisited-${cardSize}.png`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(href), 5000);
    toast(t('saved'));
  }

  async function copyCard() {
    if (!cardBlob || !window.ClipboardItem) return toast(t('copyImageFail'));
    try {
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': cardBlob })]);
      toast(t('copiedImage'));
    } catch {
      toast(t('copyImageFail'));
    }
  }

  async function systemShare() {
    if (!cardBlob) return;
    const file = new File([cardBlob], 'earthvisited.png', { type: 'image/png' });
    try {
      await navigator.share({ files: [file], text: shareMessage(), url: shareUrl() });
    } catch (err) {
      if (err && err.name === 'AbortError') return;
      try {
        await navigator.share({ text: shareMessage(), url: shareUrl() });
      } catch { /* user dismissed */ }
    }
  }

  /* ---------------- misc UI ---------------- */
  let toastTimer;
  function toast(msg) {
    const el = $('toast');
    el.textContent = msg;
    el.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => (el.hidden = true), 2200);
  }

  async function share() {
    const url = shareUrl();
    history.replaceState(null, '', url);
    try {
      await navigator.clipboard.writeText(url);
      toast(t('copied'));
    } catch {
      toast(t('copyFail'));
    }
  }

  function applyLang() {
    const meta = LANGS.find((l) => l.code === lang) || LANGS[0];
    document.documentElement.lang = lang;
    document.documentElement.dir = meta.dir || 'ltr'; // Arabic reads right to left
    document.title = t('title');
    for (const el of document.querySelectorAll('[data-i18n]')) el.textContent = t(el.dataset.i18n);
    for (const el of document.querySelectorAll('[data-i18n-ph]')) el.placeholder = t(el.dataset.i18nPh);
    if (detail) $('search').placeholder = t('searchSub');
    for (const el of document.querySelectorAll('[data-i18n-title]')) el.title = t(el.dataset.i18nTitle);
    if (resetArmed) disarmReset();
    $('hint').textContent = hintText();
    if (detail) $('crumbName').textContent = nameOf(byCode.get(detail.code));
    buildList();
    // the city rows went with the list; they come back in the new language
    if (cityData) {
      const q = fold($('search').value.trim());
      if (q.length >= 2) ensureCityNames(lang).then(() => showCityMatches(q));
      drawCities();
    }
    if (worldSubs) ensureSubNames(lang).then(() => buildList());
    updateScore();
    if ($('settings').open) renderSettings();
    if ($('sheet').open) {
      renderSizes();
      renderCard();
    }
  }

  function disarmReset() {
    clearTimeout(resetTimer);
    resetArmed = false;
    $('resetBtn').textContent = t('reset');
    $('resetBtn').classList.remove('danger');
  }

  function applyTheme() {
    const resolved = theme === 'auto' ? (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark') : theme;
    document.documentElement.dataset.theme = resolved;
    applyColors();
    redrawGlobe();
  }

  // Remember what the stylesheet says before any override, so "reset" can restore it.
  function readDefaultColors() {
    for (const l of LEVELS) {
      document.documentElement.style.removeProperty(`--lv${l.id}`);
      DEFAULT_COLORS[l.id] = cssVar(`--lv${l.id}`);
    }
  }

  function applyColors() {
    readDefaultColors();
    for (const l of LEVELS) {
      if (colors[l.id]) document.documentElement.style.setProperty(`--lv${l.id}`, colors[l.id]);
    }
  }

  /* ---------------- settings ---------------- */
  function optionButton(label, active, onPick) {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'opt';
    b.classList.toggle('on', active);
    b.setAttribute('aria-pressed', String(active));
    b.textContent = label;
    b.onclick = onPick;
    return b;
  }

  function renderSettings() {
    $('langOpts').replaceChildren(
      ...LANGS.map((l) =>
        optionButton(l.label, lang === l.code, () => {
          lang = l.code;
          savePrefs();
          applyLang();
          renderSettings();
        })
      )
    );

    $('themeOpts').replaceChildren(
      ...['dark', 'light', 'auto'].map((mode) =>
        optionButton(t(mode), theme === mode, () => {
          theme = mode;
          savePrefs();
          applyTheme();
          renderSettings();
        })
      )
    );

    $('colorList').replaceChildren(
      ...LEVELS.map((l) => {
        const row = document.createElement('label');
        row.className = 'colorrow';
        const swatch = document.createElement('input');
        swatch.type = 'color';
        swatch.value = colors[l.id] || DEFAULT_COLORS[l.id] || '#34d399';
        swatch.oninput = () => {
          colors[l.id] = swatch.value;
          applyColors();
          savePrefs();
          repaintLevelColors();
        };
        const name = document.createElement('b');
        name.textContent = t(l.key);
        const count = document.createElement('span');
        count.textContent = lastCounts ? lastCounts[l.id] || 0 : 0;
        row.append(swatch, name, count);
        return row;
      })
    );
  }

  // colours live in CSS variables, so only the pieces drawn from JS need a nudge
  function repaintLevelColors() {
    redrawGlobe();
    renderBrush(lastCounts);
    if ($('sheet').open) renderCard();
  }

  function init() {
    worldSubtitle = $('scoreSub').innerHTML; // before any view rewrites it
    loadPrefs();
    load();
    applyTheme();
    buildMap();
    applyView();
    initZoom();
    applyLang();
    for (const code of marks.keys()) paintShape(code);
    applyPendingSub();
    applyPendingCities();
    if (cityMarks.size) ensureCities().then(drawCities); // marks restored from storage

    $('search').addEventListener('input', (e) => filterList(e.target.value));
    $('search').addEventListener('keydown', (e) => {
      if (e.key !== 'Enter') return;
      const row = [...list.querySelectorAll('.row')].find((r) => !r.hidden);
      if (row) {
        toggle(row.dataset.code);
        e.target.select();
      }
    });
    // two-step reset instead of a browser confirm(): the second tap does it
    $('resetBtn').onclick = () => {
      const nothing = detail ? !detailCount() : grain === 'sub' ? !subMarks.size : !marks.size && !subMarks.size && !cityMarks.size;
      if (nothing) return;
      if (!resetArmed) {
        resetArmed = true;
        $('resetBtn').textContent = t('resetAsk');
        $('resetBtn').classList.add('danger');
        clearTimeout(resetTimer);
        resetTimer = setTimeout(disarmReset, 3500);
        return;
      }
      disarmReset();
      if (detail) {
        // inside a country, Reset means "this country's provinces", not the world
        for (const unit of detail.units) subMarks.delete(unit.c);
        for (const id of detail.byId.keys()) paintSub(id);
      } else if (grain === 'sub') {
        // and in the city view it means the provinces, not the countries
        const all = [...subMarks.keys()];
        subMarks.clear();
        all.forEach(paintSub);
        buildList();
      } else {
        const all = [...marks.keys()];
        marks.clear();
        subMarks.clear(); // otherwise provinces would linger, invisible, in the next link
        cityMarks.clear();
        drawCities();
        all.forEach(paintShape);
        all.forEach(paintRow);
      }
      updateScore();
      updateHeads();
      save();
    };
    $('crumbBack').onclick = () => closeDetail();
    $('viewMap').onclick = () => setView('map');
    $('viewGlobe').onclick = () => setView('globe');
    $('grainCountry').onclick = () => setGrain('country');
    $('grainSub').onclick = () => setGrain('sub');
    if (mode !== 'map' || grain !== 'country') {
      const view = mode;
      const want = grain;
      mode = 'map'; // the setters do the switching work, including the lazy loads
      grain = 'country';
      setView(view).then(() => setGrain(want));
    }
    // a country's provinces are a flat-map thing; the globe closes them
    $('viewGlobe').addEventListener('click', () => detail && closeDetail());

    $('settingsBtn').onclick = () => {
      renderSettings();
      const dlg = $('settings');
      if (typeof dlg.showModal === 'function') dlg.showModal();
      else dlg.setAttribute('open', '');
    };
    $('settingsClose').onclick = () => $('settings').close();
    $('settings').addEventListener('click', (e) => {
      if (e.target === $('settings')) $('settings').close();
    });
    $('resetColors').onclick = () => {
      colors = {};
      applyColors();
      savePrefs();
      renderSettings();
      repaintLevelColors();
    };
    matchMedia('(prefers-color-scheme: light)').addEventListener('change', () => {
      if (theme === 'auto') applyTheme();
    });

    $('shareBtn').onclick = openShare;
    $('sheetClose').onclick = () => $('sheet').close();
    $('sheet').addEventListener('click', (e) => {
      if (e.target === $('sheet')) $('sheet').close(); // click on the backdrop
    });
    $('copyLink').onclick = share;
    $('saveImg').onclick = saveCard;
    $('copyImg').onclick = copyCard;
    $('sysShare').onclick = systemShare;
    addEventListener('resize', sizeMarkers);
    addEventListener('hashchange', () => {
      const codes = fromHash();
      if (!codes) return;
      const touched = new Set([...marks.keys(), ...codes.map(([c]) => c)]);
      marks.clear();
      codes.forEach(([c, lv]) => byCode.has(c) && marks.set(c, lv));
      touched.forEach(paintShape);
      touched.forEach(paintRow);
      updateScore();
      save();
    });
  }

  document.addEventListener('DOMContentLoaded', init);

  // Offline support in production. On localhost it is switched off and any worker
  // left from an earlier visit is removed: a cached shell there means edits appear
  // not to happen, which is a miserable way to spend an afternoon. `?sw=1` turns it
  // back on locally, which is how the browser tests exercise it.
  if ('serviceWorker' in navigator && location.protocol.startsWith('http')) {
    const local = /^(localhost|127\.0\.0\.1|\[::1\])$/.test(location.hostname);
    const wanted = !local || new URLSearchParams(location.search).get('sw') === '1';
    addEventListener('load', async () => {
      if (wanted) {
        navigator.serviceWorker.register('sw.js').catch(() => {});
        return;
      }
      for (const reg of await navigator.serviceWorker.getRegistrations()) reg.unregister();
      if (window.caches) for (const key of await caches.keys()) caches.delete(key);
    });
  }
})();
