/* EarthVisited — click the countries you've been to.
   Data comes from js/data.js (generated by tools/gen.mjs):
     WORLD = { w, h, decor:[pathData], f:[ {c,n,t,g,r,s,a,x,y,d} ] }
     c=ISO alpha-2  n=English name  t=Turkish name  g=flag  r=region
     s=1 sovereign / 2 territory    a=projected area  x,y=centroid  d=SVG path
*/
(() => {
  'use strict';

  const SVG_NS = 'http://www.w3.org/2000/svg';
  const STORE_KEY = 'earthvisited:v1';
  const PREF_KEY = 'earthvisited:prefs';
  const DOT_AREA = 6; // entities smaller than this get a clickable dot
  const DRAG_SLOP = 4; // px of movement before a press counts as a pan, not a tap
  const MAX_ZOOM = 40;

  const W = WORLD.w;
  const H = WORLD.h;
  const FEATURES = WORLD.f;
  const byCode = new Map(FEATURES.map((f) => [f.c, f]));
  const SOVEREIGN_TOTAL = FEATURES.filter((f) => f.s === 1).length;
  const SHARE_ORDER = FEATURES.map((f) => f.c).sort(); // stable bit order for share links

  const REGION_BOX = WORLD.regions;
  const REGIONS = ['Africa', 'Americas', 'Asia', 'Europe', 'Oceania'];
  const REGION_TOTAL = {};
  for (const r of REGIONS) REGION_TOTAL[r] = FEATURES.filter((f) => f.s === 1 && f.r === r).length;

  /* ---------------- i18n ---------------- */
  const I18N = {
    en: {
      title: 'EarthVisited — mark the countries you have visited',
      countries: 'countries visited',
      territories: 'territories',
      search: 'Search a country…',
      reset: 'Reset',
      share: 'Copy link',
      download: 'Download PNG',
      hint: 'Click a country · scroll to zoom · drag to pan',
      theme: 'Switch theme',
      territory: 'territory',
      noResults: 'No match',
      copied: 'Link copied to clipboard',
      copyFail: 'Could not copy — link is in the address bar',
      resetAsk: 'Clear all selected countries?',
      saved: 'Image saved',
      exportTitle: 'Countries I have visited',
      allRegions: 'Whole world',
      shareOpen: 'Share',
      shareTitle: 'Share your map',
      shareImage: 'Share image',
      saveImage: 'Save image',
      copyImage: 'Copy image',
      copiedImage: 'Image copied to clipboard',
      copyImageFail: 'Copying images is not supported here — save it instead',
      shareNote: 'Share image opens your device\u2019s share menu — Instagram, WhatsApp, X and the rest live there. If your browser has no share menu, save or copy the card and attach it yourself.',
      sizeLink: 'Landscape',
      sizeSquare: 'Square',
      sizeStory: 'Story',
      cardTitle: 'Countries I have visited',
      cardMore: '+{n} more',
      shareText: "I've visited {n} of the world's {total} countries ({pct}%). How many have you seen?",
      headSel: 'Selected',
      headRest: 'All countries',
      of: 'of',
      other: 'Other',
    },
    tr: {
      title: 'EarthVisited — gezdiğiniz ülkeleri işaretleyin',
      countries: 'ülke gezildi',
      territories: 'bağımlı bölge',
      search: 'Ülke ara…',
      reset: 'Sıfırla',
      share: 'Bağlantıyı kopyala',
      download: "PNG'yi indir",
      hint: 'Ülkeye tıklayın · yakınlaştırmak için kaydırın · sürükleyin',
      theme: 'Temayı değiştir',
      territory: 'bölge',
      noResults: 'Sonuç yok',
      copied: 'Bağlantı kopyalandı',
      copyFail: 'Kopyalanamadı — bağlantı adres çubuğunda',
      resetAsk: 'Seçili tüm ülkeler silinsin mi?',
      saved: 'Görsel kaydedildi',
      exportTitle: 'Gezdiğim ülkeler',
      allRegions: 'Tüm dünya',
      shareOpen: 'Paylaş',
      shareTitle: 'Haritanı paylaş',
      shareImage: 'Görseli paylaş',
      saveImage: 'Görseli kaydet',
      copyImage: 'Görseli kopyala',
      copiedImage: 'Görsel panoya kopyalandı',
      copyImageFail: 'Burada görsel kopyalanamıyor — kaydedip kullanabilirsin',
      shareNote: 'Görseli paylaş, cihazının paylaşım menüsünü açar — Instagram, WhatsApp, X ve diğerleri orada. Tarayıcında paylaşım menüsü yoksa kartı kaydedip veya kopyalayıp kendin ekleyebilirsin.',
      sizeLink: 'Yatay',
      sizeSquare: 'Kare',
      sizeStory: 'Hikâye',
      cardTitle: 'Gezdiğim ülkeler',
      cardMore: '+{n} ülke daha',
      shareText: 'Dünyadaki {total} ülkenin {n} tanesini gezdim (%{pct}). Sen kaç ülke gezdin?',
      headSel: 'Seçilenler',
      headRest: 'Tüm ülkeler',
      of: '/',
      other: 'Diğer',
    },
  };
  const REGION_NAMES = {
    en: { Africa: 'Africa', Americas: 'Americas', Asia: 'Asia', Europe: 'Europe', Oceania: 'Oceania' },
    tr: { Africa: 'Afrika', Americas: 'Amerika', Asia: 'Asya', Europe: 'Avrupa', Oceania: 'Okyanusya' },
  };

  let lang = 'en';
  let theme = 'dark';
  const t = (k) => I18N[lang][k];
  const nameOf = (f) => (lang === 'tr' ? f.t : f.n);

  /* ---------------- state ---------------- */
  const picked = new Set();
  const els = {}; // code -> { shape, row }
  let activeRegion = null; // continent filter, or null for the whole world
  let regionCounts = {};
  let animTimer;
  let cardSize = 'link';
  let cardBlob = null; // PNG for the size currently previewed

  const $ = (id) => document.getElementById(id);
  const map = $('map');
  const mapwrap = $('mapwrap');
  const tip = $('tip');
  const list = $('list');

  /* ---------------- persistence ---------------- */
  function encodeShare() {
    const bytes = new Uint8Array(Math.ceil(SHARE_ORDER.length / 8));
    SHARE_ORDER.forEach((code, i) => {
      if (picked.has(code)) bytes[i >> 3] |= 1 << (i & 7);
    });
    let bin = '';
    for (const b of bytes) bin += String.fromCharCode(b);
    return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }

  function decodeShare(s) {
    try {
      const bin = atob(s.replace(/-/g, '+').replace(/_/g, '/'));
      const out = [];
      SHARE_ORDER.forEach((code, i) => {
        const byte = bin.charCodeAt(i >> 3);
        if (byte & (1 << (i & 7))) out.push(code);
      });
      return out;
    } catch {
      return null;
    }
  }

  function save() {
    try {
      localStorage.setItem(STORE_KEY, [...picked].join(','));
    } catch { /* private mode */ }
  }

  function savePrefs() {
    try {
      localStorage.setItem(PREF_KEY, JSON.stringify({ lang, theme }));
    } catch { /* private mode */ }
  }

  function load() {
    const hash = location.hash.match(/^#v1=([\w-]+)/);
    const fromHash = hash && decodeShare(hash[1]);
    if (fromHash && fromHash.length) {
      fromHash.forEach((c) => byCode.has(c) && picked.add(c));
      return;
    }
    try {
      const raw = localStorage.getItem(STORE_KEY);
      if (raw) raw.split(',').forEach((c) => byCode.has(c) && picked.add(c));
    } catch { /* private mode */ }
  }

  function loadPrefs() {
    let saved = null;
    try {
      saved = JSON.parse(localStorage.getItem(PREF_KEY) || 'null');
    } catch { /* ignore */ }
    const guess = (navigator.language || '').toLowerCase().startsWith('tr') ? 'tr' : 'en';
    lang = saved?.lang === 'tr' || saved?.lang === 'en' ? saved.lang : guess;
    theme = saved?.theme || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark');
    // ?lang=tr / ?theme=light let a shared link pick how it opens
    const q = new URLSearchParams(location.search);
    if (q.get('lang') === 'tr' || q.get('lang') === 'en') lang = q.get('lang');
    if (q.get('theme') === 'light' || q.get('theme') === 'dark') theme = q.get('theme');
  }

  /* ---------------- map ---------------- */
  const scene = document.createElementNS(SVG_NS, 'g');
  scene.setAttribute('class', 'scene');

  function buildMap() {
    map.setAttribute('viewBox', `0 0 ${W} ${H}`);
    map.setAttribute('preserveAspectRatio', 'xMidYMid meet');

    const decorG = document.createElementNS(SVG_NS, 'g');
    for (const d of WORLD.decor) {
      const p = document.createElementNS(SVG_NS, 'path');
      p.setAttribute('d', d);
      p.setAttribute('class', 'land decor');
      decorG.appendChild(p);
    }

    const landG = document.createElementNS(SVG_NS, 'g');
    const dotG = document.createElementNS(SVG_NS, 'g');
    dotG.setAttribute('id', 'dots');

    for (const f of FEATURES) {
      let shape;
      if (f.d) {
        shape = document.createElementNS(SVG_NS, 'path');
        shape.setAttribute('d', f.d);
        shape.setAttribute('class', 'land pickable');
        landG.appendChild(shape);
      }
      if (f.a < DOT_AREA) {
        const dot = document.createElementNS(SVG_NS, 'circle');
        dot.setAttribute('cx', f.x);
        dot.setAttribute('cy', f.y);
        dot.setAttribute('r', 2.6);
        dot.setAttribute('class', 'dot');
        dot.dataset.code = f.c;
        dotG.appendChild(dot);
        if (!shape) shape = dot;
        else els[f.c] = { extra: dot };
      }
      if (shape) shape.dataset.code = f.c;
      els[f.c] = Object.assign(els[f.c] || {}, { shape });
    }

    scene.append(decorG, landG, dotG);
    map.appendChild(scene);
    map.addEventListener('pointermove', onMapHover);
    map.addEventListener('pointerleave', hideTip);
  }

  function shapesOf(code) {
    const e = els[code];
    return e ? [e.shape, e.extra].filter(Boolean) : [];
  }

  function paintShape(code) {
    const on = picked.has(code);
    for (const s of shapesOf(code)) s.classList.toggle('on', on);
  }

  /* ---------------- zoom & pan ---------------- */
  const view = { k: 1, x: 0, y: 0 };
  const pointers = new Map();
  let dragged = 0;
  let pinchStart = null;
  let pressCode = null;

  function applyView() {
    view.x = Math.min(0, Math.max(W - W * view.k, view.x));
    view.y = Math.min(0, Math.max(H - H * view.k, view.y));
    scene.setAttribute('transform', `translate(${view.x} ${view.y}) scale(${view.k})`);
    const r = Math.max(0.5, 2.6 / view.k);
    for (const dot of map.querySelectorAll('#dots circle')) dot.setAttribute('r', r);
  }

  function svgPoint(evt) {
    const ctm = map.getScreenCTM();
    if (!ctm) return { x: 0, y: 0 };
    const inv = ctm.inverse();
    return { x: evt.clientX * inv.a + evt.clientY * inv.c + inv.e, y: evt.clientX * inv.b + evt.clientY * inv.d + inv.f };
  }

  function zoomAt(px, py, factor) {
    const k = Math.min(MAX_ZOOM, Math.max(1, view.k * factor));
    if (k === view.k) return;
    view.x = px - ((px - view.x) * k) / view.k;
    view.y = py - ((py - view.y) * k) / view.k;
    view.k = k;
    applyView();
  }

  function initZoom() {
    mapwrap.addEventListener(
      'wheel',
      (e) => {
        e.preventDefault();
        const p = svgPoint(e);
        zoomAt(p.x, p.y, Math.exp(-e.deltaY * (e.deltaMode === 1 ? 0.05 : 0.002)));
      },
      { passive: false }
    );

    map.addEventListener('pointerdown', (e) => {
      pointers.set(e.pointerId, e);
      dragged = 0;
      // Remember what was under the finger/cursor: the toggle happens on pointerup,
      // because capturing the pointer for panning would retarget a later click event.
      pressCode = pointers.size === 1 ? (e.target.dataset && e.target.dataset.code) || null : null;
      if (pointers.size === 2) {
        const [a, b] = [...pointers.values()];
        pinchStart = { dist: Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY), k: view.k };
      }
    });

    map.addEventListener('pointermove', (e) => {
      if (!pointers.has(e.pointerId)) return;
      const prev = pointers.get(e.pointerId);
      pointers.set(e.pointerId, e);

      if (pointers.size === 2 && pinchStart) {
        const [a, b] = [...pointers.values()];
        const dist = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
        const mid = svgPoint({ clientX: (a.clientX + b.clientX) / 2, clientY: (a.clientY + b.clientY) / 2 });
        const target = Math.min(MAX_ZOOM, Math.max(1, (pinchStart.k * dist) / pinchStart.dist));
        zoomAt(mid.x, mid.y, target / view.k);
        dragged = 99;
        return;
      }

      const ctm = map.getScreenCTM();
      if (!ctm) return;
      const sx = (e.clientX - prev.clientX) / ctm.a;
      const sy = (e.clientY - prev.clientY) / ctm.d;
      dragged += Math.abs(e.clientX - prev.clientX) + Math.abs(e.clientY - prev.clientY);
      if (dragged > DRAG_SLOP && !map.hasPointerCapture(e.pointerId)) {
        map.setPointerCapture(e.pointerId); // only now, so a plain click stays a click
        map.classList.add('dragging');
      }
      view.x += sx;
      view.y += sy;
      applyView();
    });

    const end = (e) => {
      pointers.delete(e.pointerId);
      if (pointers.size < 2) pinchStart = null;
      if (!pointers.size) map.classList.remove('dragging');
      if (e.type === 'pointerup' && pressCode && dragged <= DRAG_SLOP) toggle(pressCode);
      pressCode = null;
    };
    map.addEventListener('pointerup', end);
    map.addEventListener('pointercancel', end);

    $('zoomIn').onclick = () => zoomAt(W / 2, H / 2, 1.6);
    $('zoomOut').onclick = () => zoomAt(W / 2, H / 2, 1 / 1.6);
    $('zoomReset').onclick = () => {
      view.k = 1;
      view.x = view.y = 0;
      applyView();
    };
  }

  /* ---------------- interaction ---------------- */
  function onMapHover(e) {
    const code = e.target.dataset && e.target.dataset.code;
    if (!code) return hideTip();
    const f = byCode.get(code);
    const rect = mapwrap.getBoundingClientRect();
    tip.innerHTML = '';
    tip.append(`${f.g ? f.g + ' ' : ''}${nameOf(f)}`);
    if (f.s !== 1) {
      const s = document.createElement('small');
      s.textContent = t('territory');
      tip.appendChild(s);
    }
    tip.hidden = false;
    tip.style.left = `${e.clientX - rect.left}px`;
    tip.style.top = `${e.clientY - rect.top}px`;
  }

  function hideTip() {
    tip.hidden = true;
  }

  function toggle(code) {
    if (!byCode.has(code)) return;
    if (picked.has(code)) picked.delete(code);
    else picked.add(code);
    paintShape(code);
    const row = els[code]?.row;
    if (row) {
      row.classList.toggle('on', picked.has(code));
      row.setAttribute('aria-pressed', String(picked.has(code)));
    }
    updateScore();
    updateHeads();
    save();
    if (location.hash) history.replaceState(null, '', location.pathname + location.search);
    $('hint').classList.add('gone');
  }

  /* ---------------- list ---------------- */
  function buildList() {
    const frag = document.createDocumentFragment();
    const sorted = [...FEATURES].sort((a, b) => nameOf(a).localeCompare(nameOf(b), lang));
    for (const f of sorted) {
      const row = document.createElement('button');
      row.type = 'button';
      row.className = 'row';
      row.dataset.code = f.c;
      row.innerHTML =
        `<span class="box"></span><span class="flag">${f.g || '🏳'}</span>` +
        `<span class="nm"></span>${f.s !== 1 ? `<span class="tag"></span>` : ''}`;
      row.querySelector('.nm').textContent = nameOf(f);
      if (f.s !== 1) row.querySelector('.tag').textContent = t('territory');
      row.classList.toggle('on', picked.has(f.c));
      row.setAttribute('aria-pressed', String(picked.has(f.c)));
      row.onclick = () => toggle(f.c);
      row.onmouseenter = () => shapesOf(f.c).forEach((s) => s.classList.add('hl'));
      row.onmouseleave = () => shapesOf(f.c).forEach((s) => s.classList.remove('hl'));
      els[f.c] = Object.assign(els[f.c] || {}, { row });
      frag.appendChild(row);
    }
    const headSel = document.createElement('div');
    headSel.className = 'lhead sel';
    headSel.id = 'headSel';
    const headRest = document.createElement('div');
    headRest.className = 'lhead';
    headRest.id = 'headRest';
    list.replaceChildren(headSel, frag, headRest);
    filterList($('search').value);
  }

  const fold = (s) =>
    s
      .toLocaleLowerCase('tr')
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/ı/g, 'i');

  function filterList(q) {
    const needle = fold(q.trim());
    let onShown = 0;
    let offShown = 0;
    for (const f of FEATURES) {
      const row = els[f.c]?.row;
      if (!row) continue;
      const matchesText =
        !needle || fold(f.n).includes(needle) || fold(f.t).includes(needle) || f.c.toLowerCase() === needle;
      const hit = matchesText && (!activeRegion || f.r === activeRegion);
      row.hidden = !hit;
      if (hit) picked.has(f.c) ? onShown++ : offShown++;
    }
    updateHeads(onShown, offShown);

    let empty = list.querySelector('.empty');
    if (!onShown && !offShown) {
      if (!empty) {
        empty = document.createElement('p');
        empty.className = 'empty';
        list.appendChild(empty);
      }
      empty.textContent = t('noResults');
      empty.hidden = false;
    } else if (empty) empty.hidden = true;
  }

  // Selected rows float to the top via CSS `order`; these two headers label the groups.
  function updateHeads(onShown, offShown) {
    if (onShown === undefined) {
      onShown = offShown = 0;
      for (const f of FEATURES) {
        const row = els[f.c]?.row;
        if (!row || row.hidden) continue;
        picked.has(f.c) ? onShown++ : offShown++;
      }
    }
    const sel = $('headSel');
    const rest = $('headRest');
    if (!sel || !rest) return;
    sel.textContent = `${t('headSel')} · ${onShown}`;
    sel.hidden = !onShown;
    rest.textContent = t('headRest');
    rest.hidden = !offShown || !onShown;
  }

  /* ---------------- continent filter ---------------- */
  function setRegion(r) {
    activeRegion = activeRegion === r ? null : r;
    for (const f of FEATURES) {
      const off = activeRegion && f.r !== activeRegion;
      for (const s of shapesOf(f.c)) s.classList.toggle('dim', !!off);
    }
    for (const p of map.querySelectorAll('.decor')) p.classList.toggle('dim', !!activeRegion);
    focusBox(activeRegion ? REGION_BOX[activeRegion] : null);
    renderRegions();
    filterList($('search').value);
    list.scrollTop = 0;
  }

  function focusBox(box) {
    scene.classList.add('anim');
    if (!box) {
      view.k = 1;
      view.x = view.y = 0;
    } else {
      const [x0, y0, x1, y1] = box;
      const k = Math.min(MAX_ZOOM, Math.max(1, Math.min(W / (x1 - x0), H / (y1 - y0))));
      view.k = k;
      view.x = W / 2 - ((x0 + x1) / 2) * k;
      view.y = H / 2 - ((y0 + y1) / 2) * k;
    }
    applyView();
    clearTimeout(animTimer);
    animTimer = setTimeout(() => scene.classList.remove('anim'), 450);
  }

  /* ---------------- score ---------------- */
  function updateScore() {
    let sov = 0;
    let terr = 0;
    const perRegion = {};
    for (const code of picked) {
      const f = byCode.get(code);
      if (!f) continue;
      if (f.s === 1) {
        sov++;
        perRegion[f.r] = (perRegion[f.r] || 0) + 1;
      } else terr++;
    }
    $('count').textContent = sov;
    $('terr').textContent = terr;
    const pct = Math.round((sov / SOVEREIGN_TOTAL) * 100);
    $('pct').textContent = `${pct}%`;
    $('barfill').style.width = `${(sov / SOVEREIGN_TOTAL) * 100}%`;

    regionCounts = perRegion;
    renderRegions();
  }

  function renderRegions() {
    const chips = REGIONS.map((r) => {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'region';
      btn.classList.toggle('on', activeRegion === r);
      btn.setAttribute('aria-pressed', String(activeRegion === r));
      const b = document.createElement('b');
      b.textContent = REGION_NAMES[lang][r];
      const s = document.createElement('span');
      s.textContent = `${regionCounts[r] || 0}/${REGION_TOTAL[r]}`;
      btn.append(b, s);
      btn.onclick = () => setRegion(r);
      return btn;
    });

    const all = document.createElement('button');
    all.type = 'button';
    all.className = 'region all';
    all.classList.toggle('on', !activeRegion);
    all.setAttribute('aria-pressed', String(!activeRegion));
    const ab = document.createElement('b');
    ab.textContent = t('allRegions');
    const as = document.createElement('span');
    as.textContent = `${$('count').textContent}/${SOVEREIGN_TOTAL}`;
    all.append(ab, as);
    all.onclick = () => activeRegion && setRegion(activeRegion);
    chips.push(all);

    $('regions').replaceChildren(...chips);
  }

  /* ---------------- share card ---------------- */
  const CARD_SIZES = [
    ['link', 'sizeLink'],
    ['square', 'sizeSquare'],
    ['story', 'sizeStory'],
  ];

  function cssVar(name) {
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  }

  function stats() {
    let sov = 0;
    let terr = 0;
    const per = {};
    for (const code of picked) {
      const f = byCode.get(code);
      if (!f) continue;
      if (f.s === 1) {
        sov++;
        per[f.r] = (per[f.r] || 0) + 1;
      } else terr++;
    }
    return { sov, terr, per, total: SOVEREIGN_TOTAL, pct: Math.round((sov / SOVEREIGN_TOTAL) * 100) };
  }

  function shareUrl() {
    return `${location.origin}${location.pathname}#v1=${encodeShare()}`;
  }

  function shareMessage() {
    const s = stats();
    return t('shareText').replace('{n}', s.sov).replace('{total}', s.total).replace('{pct}', s.pct);
  }

  function buildCardSVG(size) {
    const s = stats();
    const selected = FEATURES.filter((f) => picked.has(f.c) && f.s === 1)
      .map(nameOf)
      .sort((a, b) => a.localeCompare(b, lang));
    return EarthCard.build({
      size,
      world: WORLD,
      picked,
      stats: s,
      regions: REGIONS.map((r) => ({ label: REGION_NAMES[lang][r], have: s.per[r] || 0, total: REGION_TOTAL[r] })),
      names: selected,
      texts: {
        title: t('cardTitle'),
        countries: t('countries'),
        territories: t('territories'),
        pct: lang === 'tr' ? `%${s.pct}` : `${s.pct}%`,
        more: t('cardMore'),
        url: (location.host + location.pathname).replace(/\/(index\.html)?$/, ''),
      },
      colors: {
        bg: cssVar('--bg-2'),
        ocean: cssVar('--ocean'),
        land: cssVar('--land'),
        on: cssVar('--picked'),
        ink: cssVar('--ink'),
        accent: cssVar('--accent'),
      },
    });
  }

  function svgToPng(svg, scale = 2) {
    return new Promise((resolve, reject) => {
      const size = svg.match(/width="(\d+)" height="(\d+)"/);
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = (size ? +size[1] : img.width) * scale;
        canvas.height = (size ? +size[2] : img.height) * scale;
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
        canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error('toBlob failed'))), 'image/png');
      };
      img.onerror = () => reject(new Error('svg load failed'));
      img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
    });
  }

  async function renderCard() {
    const svg = buildCardSVG(cardSize);
    $('cardImg').src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
    $('cardImg').alt = shareMessage();
    cardBlob = null;
    try {
      cardBlob = await svgToPng(svg, cardSize === 'link' ? 2 : 1.5);
    } catch {
      cardBlob = null;
    }
    updateShareButtons();
  }

  function canSharePng() {
    if (!navigator.canShare || !cardBlob) return false;
    try {
      return navigator.canShare({ files: [new File([cardBlob], 'earthvisited.png', { type: 'image/png' })] });
    } catch {
      return false;
    }
  }

  function updateShareButtons() {
    $('sysShare').hidden = !canSharePng();
    $('saveImg').disabled = !cardBlob;
    $('copyImg').disabled = !cardBlob || !window.ClipboardItem;
  }

  function renderSizes() {
    $('sizes').replaceChildren(
      ...CARD_SIZES.map(([key, label]) => {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = 'size';
        b.classList.toggle('on', cardSize === key);
        b.setAttribute('aria-pressed', String(cardSize === key));
        b.textContent = t(label);
        b.onclick = () => {
          cardSize = key;
          renderSizes();
          renderCard();
        };
        return b;
      })
    );
  }

  function openShare() {
    history.replaceState(null, '', shareUrl());
    cardSize = cardSize || 'link';
    renderSizes();
    renderCard();
    const sheet = $('sheet');
    if (typeof sheet.showModal === 'function') sheet.showModal();
    else sheet.setAttribute('open', '');
  }

  function saveCard() {
    if (!cardBlob) return;
    const href = URL.createObjectURL(cardBlob);
    const a = document.createElement('a');
    a.href = href;
    a.download = `earthvisited-${cardSize}.png`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(href), 5000);
    toast(t('saved'));
  }

  async function copyCard() {
    if (!cardBlob || !window.ClipboardItem) return toast(t('copyImageFail'));
    try {
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': cardBlob })]);
      toast(t('copiedImage'));
    } catch {
      toast(t('copyImageFail'));
    }
  }

  async function systemShare() {
    if (!cardBlob) return;
    const file = new File([cardBlob], 'earthvisited.png', { type: 'image/png' });
    try {
      await navigator.share({ files: [file], text: shareMessage(), url: shareUrl() });
    } catch (err) {
      if (err && err.name === 'AbortError') return;
      try {
        await navigator.share({ text: shareMessage(), url: shareUrl() });
      } catch { /* user dismissed */ }
    }
  }

  /* ---------------- misc UI ---------------- */
  let toastTimer;
  function toast(msg) {
    const el = $('toast');
    el.textContent = msg;
    el.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => (el.hidden = true), 2200);
  }

  async function share() {
    const url = shareUrl();
    history.replaceState(null, '', url);
    try {
      await navigator.clipboard.writeText(url);
      toast(t('copied'));
    } catch {
      toast(t('copyFail'));
    }
  }

  function applyLang() {
    document.documentElement.lang = lang;
    document.title = t('title');
    for (const el of document.querySelectorAll('[data-i18n]')) el.textContent = t(el.dataset.i18n);
    for (const el of document.querySelectorAll('[data-i18n-ph]')) el.placeholder = t(el.dataset.i18nPh);
    for (const el of document.querySelectorAll('[data-i18n-title]')) el.title = t(el.dataset.i18nTitle);
    $('langBtn').textContent = lang === 'en' ? 'TR' : 'EN';
    $('langBtn').title = lang === 'en' ? 'Türkçe' : 'English';
    buildList();
    updateScore();
    if ($('sheet').open) {
      renderSizes();
      renderCard();
    }
  }

  function applyTheme() {
    document.documentElement.dataset.theme = theme;
  }

  function init() {
    loadPrefs();
    load();
    applyTheme();
    buildMap();
    applyView();
    initZoom();
    applyLang();
    for (const code of picked) paintShape(code);

    $('search').addEventListener('input', (e) => filterList(e.target.value));
    $('search').addEventListener('keydown', (e) => {
      if (e.key !== 'Enter') return;
      const row = [...list.querySelectorAll('.row')].find((r) => !r.hidden);
      if (row) {
        toggle(row.dataset.code);
        e.target.select();
      }
    });
    $('resetBtn').onclick = () => {
      if (!picked.size || !confirm(t('resetAsk'))) return;
      const all = [...picked];
      picked.clear();
      all.forEach(paintShape);
      all.forEach((c) => els[c]?.row?.classList.remove('on'));
      updateScore();
      save();
    };
    $('shareBtn').onclick = openShare;
    $('sheetClose').onclick = () => $('sheet').close();
    $('sheet').addEventListener('click', (e) => {
      if (e.target === $('sheet')) $('sheet').close(); // click on the backdrop
    });
    $('copyLink').onclick = share;
    $('saveImg').onclick = saveCard;
    $('copyImg').onclick = copyCard;
    $('sysShare').onclick = systemShare;
    $('langBtn').onclick = () => {
      lang = lang === 'en' ? 'tr' : 'en';
      savePrefs();
      applyLang();
    };
    $('themeBtn').onclick = () => {
      theme = theme === 'dark' ? 'light' : 'dark';
      savePrefs();
      applyTheme();
    };
    addEventListener('hashchange', () => {
      const m = location.hash.match(/^#v1=([\w-]+)/);
      const codes = m && decodeShare(m[1]);
      if (!codes) return;
      const all = new Set([...picked, ...codes]);
      picked.clear();
      codes.forEach((c) => byCode.has(c) && picked.add(c));
      all.forEach(paintShape);
      all.forEach((c) => els[c]?.row?.classList.toggle('on', picked.has(c)));
      updateScore();
      save();
    });
  }

  document.addEventListener('DOMContentLoaded', init);
})();
