/* EarthVisited — click the countries you've been to.
   Data comes from js/data.js (generated by tools/gen.mjs):
     WORLD = { w, h, decor:[pathData], f:[ {c,n,t,g,r,s,a,x,y,d} ] }
     c=ISO alpha-2  n=English name  t=Turkish name  g=flag  r=region
     s=1 sovereign / 2 territory    a=projected area  x,y=centroid  d=SVG path
*/
(() => {
  'use strict';

  const SVG_NS = 'http://www.w3.org/2000/svg';
  const STORE_KEY = 'earthvisited:v1';
  const PREF_KEY = 'earthvisited:prefs';
  const DOT_AREA = 6; // entities smaller than this get a clickable dot
  const DRAG_SLOP = 4; // px of movement before a press counts as a pan, not a tap
  const MAX_ZOOM = 24; // past this the 1:50m coastlines run out of detail

  const W = WORLD.w;
  const H = WORLD.h;
  const FEATURES = WORLD.f;
  const byCode = new Map(FEATURES.map((f) => [f.c, f]));
  // s: 1 UN member (or observer state), 3 counted as a country anyway, 2 territory
  const isCountry = (f) => f.s === 1 || f.s === 3;
  const SOVEREIGN_TOTAL = FEATURES.filter(isCountry).length;
  const WORLD_LAND = WORLD.totals.k; // km², every entity on the map
  const WORLD_POP = WORLD.totals.p;
  // Bit order for share links. data.js pins it so that entities added later land at
  // the end and older links keep decoding to the same countries.
  const SHARE_ORDER = WORLD.order || FEATURES.map((f) => f.c).sort();

  const REGION_BOX = WORLD.regions;
  const REGIONS = ['Africa', 'Americas', 'Asia', 'Europe', 'Oceania'];
  const REGION_TOTAL = {};
  for (const r of REGIONS) REGION_TOTAL[r] = FEATURES.filter((f) => isCountry(f) && f.r === r).length;

  /* ---------------- i18n ---------------- */
  const LANGS = I18N.list;
  const STRINGS = I18N.s;
  const REGION_NAMES = I18N.regions;
  const DEFAULT_COLORS = {}; // filled from the stylesheet on first paint

  let lang = 'en';
  let theme = 'auto'; // 'dark' | 'light' | 'auto'
  let colors = {}; // level id -> custom hex, empty means the stylesheet default
  const t = (k) => STRINGS[lang][k] ?? STRINGS.en[k] ?? k;
  const nameOf = (f) => (f.L && f.L[lang]) || f.n;
  const localeOf = () => (LANGS.find((l) => l.code === lang) || LANGS[0]).locale;

  /* ---------------- state ---------------- */
  // 0 = unmarked. 1..3 all mean "I have been there" and feed the score; 4 is a wish.
  const LEVELS = [
    { id: 1, key: 'lived' },
    { id: 2, key: 'visited' },
    { id: 3, key: 'transit' },
    { id: 4, key: 'wish' },
  ];
  const BEEN = new Set([1, 2, 3]);
  const marks = new Map(); // code -> level
  let brush = 2; // the level a click paints with
  const been = (code) => BEEN.has(marks.get(code));
  const els = {}; // code -> { shape, row }
  let activeRegion = null; // continent filter, or null for the whole world
  let regionCounts = {};
  let lastCounts = null;
  let resetArmed = false;
  let resetTimer;
  let animTimer;
  let cardSize = 'link';
  let cardBlob = null; // PNG for the size currently previewed

  const $ = (id) => document.getElementById(id);

  // Most flags are emoji; entities without one (Northern Cyprus) ship an SVG.
  function flagNode(f, cls = 'flag') {
    if (f.fi) {
      const img = document.createElement('img');
      img.className = cls;
      img.src = f.fi;
      img.alt = '';
      return img;
    }
    const span = document.createElement('span');
    span.className = cls;
    span.textContent = f.g || '🏳';
    return span;
  }
  const map = $('map');
  const mapwrap = $('mapwrap');
  const tip = $('tip');
  const list = $('list');

  /* ---------------- persistence ---------------- */
  const toB64 = (bytes) => {
    let bin = '';
    for (const b of bytes) bin += String.fromCharCode(b);
    return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  };
  const fromB64 = (s) => atob(s.replace(/-/g, '+').replace(/_/g, '/'));

  // v2: three bits per entity, so every level survives a link.
  function encodeShare() {
    const bytes = new Uint8Array(Math.ceil((SHARE_ORDER.length * 3) / 8));
    SHARE_ORDER.forEach((code, i) => {
      const lv = marks.get(code) || 0;
      for (let b = 0; b < 3; b++) {
        if (lv & (1 << b)) {
          const at = i * 3 + b;
          bytes[at >> 3] |= 1 << (at & 7);
        }
      }
    });
    return toB64(bytes);
  }

  function decodeShare(s) {
    try {
      const bin = fromB64(s);
      const out = [];
      SHARE_ORDER.forEach((code, i) => {
        let lv = 0;
        for (let b = 0; b < 3; b++) {
          const at = i * 3 + b;
          if (bin.charCodeAt(at >> 3) & (1 << (at & 7))) lv |= 1 << b;
        }
        if (lv >= 1 && lv <= 4) out.push([code, lv]);
      });
      return out;
    } catch {
      return null;
    }
  }

  // v1 links predate levels: every bit set means "visited".
  function decodeShareV1(s) {
    try {
      const bin = fromB64(s);
      const out = [];
      SHARE_ORDER.forEach((code, i) => {
        if (bin.charCodeAt(i >> 3) & (1 << (i & 7))) out.push([code, 2]);
      });
      return out;
    } catch {
      return null;
    }
  }

  function save() {
    try {
      localStorage.setItem(STORE_KEY, [...marks].map(([c, lv]) => c + lv).join(','));
    } catch { /* private mode */ }
  }

  function savePrefs() {
    try {
      localStorage.setItem(PREF_KEY, JSON.stringify({ lang, theme, colors }));
    } catch { /* private mode */ }
  }

  function fromHash() {
    const m = location.hash.match(/^#v([12])=([\w-]+)/);
    if (!m) return null;
    const list = m[1] === '2' ? decodeShare(m[2]) : decodeShareV1(m[2]);
    return list && list.length ? list : null;
  }

  function load() {
    const shared = fromHash();
    if (shared) {
      shared.forEach(([c, lv]) => byCode.has(c) && marks.set(c, lv));
      return;
    }
    try {
      const raw = localStorage.getItem(STORE_KEY);
      if (!raw) return;
      for (const entry of raw.split(',')) {
        // entries are CODE + level; the pre-levels format stored a bare CODE
        const code = entry.slice(0, 2);
        const lv = entry.length > 2 ? +entry.slice(2) : 2;
        if (byCode.has(code) && lv >= 1 && lv <= 4) marks.set(code, lv);
      }
    } catch { /* private mode */ }
  }

  function loadPrefs() {
    let saved = null;
    try {
      saved = JSON.parse(localStorage.getItem(PREF_KEY) || 'null');
    } catch { /* ignore */ }
    const known = (c) => LANGS.some((l) => l.code === c);
    const guess = (navigator.language || '').slice(0, 2).toLowerCase();
    lang = known(saved?.lang) ? saved.lang : known(guess) ? guess : 'en';
    theme = ['dark', 'light', 'auto'].includes(saved?.theme) ? saved.theme : 'auto';
    colors = saved && typeof saved.colors === 'object' && saved.colors ? { ...saved.colors } : {};
    // ?lang=de / ?theme=light let a shared link pick how it opens
    const q = new URLSearchParams(location.search);
    if (known(q.get('lang'))) lang = q.get('lang');
    if (['dark', 'light', 'auto'].includes(q.get('theme'))) theme = q.get('theme');
  }

  /* ---------------- map ---------------- */
  const scene = document.createElementNS(SVG_NS, 'g');
  scene.setAttribute('class', 'scene');

  function buildMap() {
    map.setAttribute('viewBox', `0 0 ${W} ${H}`);
    map.setAttribute('preserveAspectRatio', 'xMidYMid meet');

    const decorG = document.createElementNS(SVG_NS, 'g');
    for (const d of WORLD.decor) {
      const p = document.createElementNS(SVG_NS, 'path');
      p.setAttribute('d', d);
      p.setAttribute('class', 'land decor');
      decorG.appendChild(p);
    }

    const landG = document.createElementNS(SVG_NS, 'g');
    const dotG = document.createElementNS(SVG_NS, 'g');
    dotG.setAttribute('id', 'dots');
    const hitG = document.createElementNS(SVG_NS, 'g');
    hitG.setAttribute('id', 'hits');

    for (const f of FEATURES) {
      let shape;
      if (f.d) {
        shape = document.createElementNS(SVG_NS, 'path');
        shape.setAttribute('d', f.d);
        shape.setAttribute('class', 'land pickable');
        landG.appendChild(shape);
      }
      if (f.a < DOT_AREA) {
        const dot = document.createElementNS(SVG_NS, 'circle');
        dot.setAttribute('cx', f.x);
        dot.setAttribute('cy', f.y);
        dot.setAttribute('r', 2.6);
        dot.setAttribute('class', 'dot');
        dot.dataset.code = f.c;
        const hit = document.createElementNS(SVG_NS, 'circle');
        hit.setAttribute('cx', f.x);
        hit.setAttribute('cy', f.y);
        hit.setAttribute('r', 7);
        hit.setAttribute('class', 'hit');
        hit.dataset.code = f.c;
        hitG.appendChild(hit);
        els[f.c] = Object.assign(els[f.c] || {}, { hit });
        dotG.appendChild(dot);
        if (!shape) shape = dot;
        else els[f.c] = { extra: dot };
      }
      if (shape) shape.dataset.code = f.c;
      els[f.c] = Object.assign(els[f.c] || {}, { shape });
    }

    scene.append(decorG, landG, dotG, hitG);
    map.appendChild(scene);
    map.addEventListener('pointermove', onMapHover);
    map.addEventListener('pointerleave', hideTip);
  }

  function shapesOf(code) {
    const e = els[code];
    return e ? [e.shape, e.extra, e.hit].filter(Boolean) : [];
  }

  function paintShape(code) {
    const lv = marks.get(code) || 0;
    for (const el of shapesOf(code)) {
      el.classList.toggle('on', lv > 0);
      for (const l of LEVELS) el.classList.toggle(`lv${l.id}`, lv === l.id);
    }
  }

  /* ---------------- zoom & pan ---------------- */
  const view = { k: 1, x: 0, y: 0 };
  const pointers = new Map();
  let dragged = 0;
  let pinchStart = null;
  let pressCode = null;
  let pressTimer = null;
  let previewed = false; // a long press showed the name, so the release must not toggle

  function applyView() {
    view.x = Math.min(0, Math.max(W - W * view.k, view.x));
    view.y = Math.min(0, Math.max(H - H * view.k, view.y));
    scene.setAttribute('transform', `translate(${view.x} ${view.y}) scale(${view.k})`);
    sizeMarkers();
  }

  // Micro-state dots are sized in screen pixels, not map units: on a phone the whole
  // world is ~390px wide, so a fixed radius would shrink to a few pixels there.
  function sizeMarkers() {
    const pxPerUnit = ((map.getBoundingClientRect().width || W) / W) * view.k;
    if (!pxPerUnit) return;
    const dotR = Math.min(13, 3.6 / pxPerUnit);
    const hitR = Math.min(24, 9 / pxPerUnit);
    for (const dot of map.querySelectorAll('#dots circle')) dot.setAttribute('r', dotR);
    for (const hit of map.querySelectorAll('#hits circle')) hit.setAttribute('r', hitR);
  }

  function svgPoint(evt) {
    const ctm = map.getScreenCTM();
    if (!ctm) return { x: 0, y: 0 };
    const inv = ctm.inverse();
    return { x: evt.clientX * inv.a + evt.clientY * inv.c + inv.e, y: evt.clientX * inv.b + evt.clientY * inv.d + inv.f };
  }

  function zoomAt(px, py, factor) {
    const k = Math.min(MAX_ZOOM, Math.max(1, view.k * factor));
    if (k === view.k) return;
    view.x = px - ((px - view.x) * k) / view.k;
    view.y = py - ((py - view.y) * k) / view.k;
    view.k = k;
    applyView();
  }

  function initZoom() {
    mapwrap.addEventListener(
      'wheel',
      (e) => {
        e.preventDefault();
        const p = svgPoint(e);
        zoomAt(p.x, p.y, Math.exp(-e.deltaY * (e.deltaMode === 1 ? 0.05 : 0.002)));
      },
      { passive: false }
    );

    map.addEventListener('pointerdown', (e) => {
      pointers.set(e.pointerId, e);
      dragged = 0;
      // Remember what was under the finger/cursor: the toggle happens on pointerup,
      // because capturing the pointer for panning would retarget a later click event.
      pressCode = pointers.size === 1 ? (e.target.dataset && e.target.dataset.code) || null : null;
      previewed = false;
      clearTimeout(pressTimer);
      if (pressCode) {
        pressTimer = setTimeout(() => {
          previewed = true;
          flash(pressCode);
          if (navigator.vibrate) navigator.vibrate(8);
        }, 420);
      }
      if (pointers.size === 2) {
        const [a, b] = [...pointers.values()];
        pinchStart = { dist: Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY), k: view.k };
      }
    });

    map.addEventListener('pointermove', (e) => {
      if (!pointers.has(e.pointerId)) return;
      const prev = pointers.get(e.pointerId);
      pointers.set(e.pointerId, e);

      if (pointers.size === 2 && pinchStart) {
        const [a, b] = [...pointers.values()];
        const dist = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
        const mid = svgPoint({ clientX: (a.clientX + b.clientX) / 2, clientY: (a.clientY + b.clientY) / 2 });
        const target = Math.min(MAX_ZOOM, Math.max(1, (pinchStart.k * dist) / pinchStart.dist));
        zoomAt(mid.x, mid.y, target / view.k);
        dragged = 99;
        return;
      }

      const ctm = map.getScreenCTM();
      if (!ctm) return;
      const sx = (e.clientX - prev.clientX) / ctm.a;
      const sy = (e.clientY - prev.clientY) / ctm.d;
      dragged += Math.abs(e.clientX - prev.clientX) + Math.abs(e.clientY - prev.clientY);
      if (dragged > DRAG_SLOP) clearTimeout(pressTimer);
      if (dragged > DRAG_SLOP && !map.hasPointerCapture(e.pointerId)) {
        map.setPointerCapture(e.pointerId); // only now, so a plain click stays a click
        map.classList.add('dragging');
      }
      view.x += sx;
      view.y += sy;
      applyView();
    });

    const end = (e) => {
      clearTimeout(pressTimer);
      pointers.delete(e.pointerId);
      if (pointers.size < 2) pinchStart = null;
      if (!pointers.size) map.classList.remove('dragging');
      if (e.type === 'pointerup' && pressCode && dragged <= DRAG_SLOP && !previewed) toggle(pressCode);
      pressCode = null;
      previewed = false;
    };
    map.addEventListener('pointerup', end);
    map.addEventListener('pointercancel', end);

    $('zoomIn').onclick = () => zoomAt(W / 2, H / 2, 1.6);
    $('zoomOut').onclick = () => zoomAt(W / 2, H / 2, 1 / 1.6);
    $('zoomReset').onclick = () => {
      view.k = 1;
      view.x = view.y = 0;
      applyView();
    };
  }

  /* ---------------- interaction ---------------- */
  function onMapHover(e) {
    const code = e.target.dataset && e.target.dataset.code;
    if (!code) return hideTip();
    const f = byCode.get(code);
    const rect = mapwrap.getBoundingClientRect();
    tip.replaceChildren(flagNode(f, 'flag tipflag'), nameOf(f));
    if (f.s === 2) {
      const s = document.createElement('small');
      s.textContent = t('territory');
      tip.appendChild(s);
    }
    tip.hidden = false;
    tip.style.left = `${e.clientX - rect.left}px`;
    tip.style.top = `${e.clientY - rect.top}px`;
  }

  function hideTip() {
    tip.hidden = true;
  }

  let flashTimer;
  // Touch screens have no hover, so name feedback rides along with the tap.
  function flash(code, state) {
    const f = byCode.get(code);
    if (!f) return;
    const el = $('flash');
    el.replaceChildren();
    const name = document.createElement('b');
    name.textContent = nameOf(f);
    el.append(flagNode(f, 'flag tipflag'), name);
    if (state !== undefined) {
      const tag = document.createElement('span');
      tag.className = state ? `on lv${state}` : 'off';
      tag.textContent = state ? t(LEVELS.find((l) => l.id === state).key) : t('cleared');
      el.appendChild(tag);
    }
    el.hidden = false;
    clearTimeout(flashTimer);
    flashTimer = setTimeout(() => (el.hidden = true), state === undefined ? 1800 : 1400);
  }

  function toggle(code) {
    if (!byCode.has(code)) return;
    // painting a country with the level it already has clears it
    const next = marks.get(code) === brush ? 0 : brush;
    if (next) marks.set(code, next);
    else marks.delete(code);
    paintShape(code);
    paintRow(code);
    flash(code, next);
    updateScore();
    updateHeads();
    save();
    if (location.hash) history.replaceState(null, '', location.pathname + location.search);
    $('hint').classList.add('gone');
  }

  function paintRow(code) {
    const row = els[code]?.row;
    if (!row) return;
    const lv = marks.get(code) || 0;
    row.classList.toggle('on', lv > 0);
    for (const l of LEVELS) row.classList.toggle(`lv${l.id}`, lv === l.id);
    row.setAttribute('aria-pressed', String(lv > 0));
  }

  /* ---------------- list ---------------- */
  function buildList() {
    const frag = document.createDocumentFragment();
    const sorted = [...FEATURES].sort((a, b) => nameOf(a).localeCompare(nameOf(b), lang));
    for (const f of sorted) {
      const row = document.createElement('button');
      row.type = 'button';
      row.className = 'row';
      row.dataset.code = f.c;
      row.innerHTML =
        `<span class="box"></span><span class="flag"></span>` +
        `<span class="nm"></span>${f.s === 2 ? `<span class="tag"></span>` : ''}`;
      row.querySelector('.flag').replaceWith(flagNode(f));
      row.querySelector('.nm').textContent = nameOf(f);
      if (f.s === 2) row.querySelector('.tag').textContent = t('territory');
      row.onclick = () => toggle(f.c);
      row.onmouseenter = () => shapesOf(f.c).forEach((s) => s.classList.add('hl'));
      row.onmouseleave = () => shapesOf(f.c).forEach((s) => s.classList.remove('hl'));
      els[f.c] = Object.assign(els[f.c] || {}, { row });
      paintRow(f.c);
      frag.appendChild(row);
    }
    const headSel = document.createElement('div');
    headSel.className = 'lhead sel';
    headSel.id = 'headSel';
    const headRest = document.createElement('div');
    headRest.className = 'lhead';
    headRest.id = 'headRest';
    list.replaceChildren(headSel, frag, headRest);
    filterList($('search').value);
  }

  const indexCache = new Map();
  const searchIndex = (f) => {
    let v = indexCache.get(f.c);
    if (v === undefined) {
      v = fold([f.n, ...Object.values(f.L || {})].join('\u0000'));
      indexCache.set(f.c, v);
    }
    return v;
  };

  const fold = (s) =>
    s
      .toLocaleLowerCase('tr')
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/ı/g, 'i');

  function filterList(q) {
    const needle = fold(q.trim());
    let onShown = 0;
    let offShown = 0;
    for (const f of FEATURES) {
      const row = els[f.c]?.row;
      if (!row) continue;
      // search every language we carry, so "Germany" finds it while the UI is Turkish
      const matchesText = !needle || f.c.toLowerCase() === needle || searchIndex(f).includes(needle);
      const hit = matchesText && (!activeRegion || f.r === activeRegion);
      row.hidden = !hit;
      if (hit) (marks.has(f.c) ? onShown++ : offShown++);
    }
    updateHeads(onShown, offShown);

    let empty = list.querySelector('.empty');
    if (!onShown && !offShown) {
      if (!empty) {
        empty = document.createElement('p');
        empty.className = 'empty';
        list.appendChild(empty);
      }
      empty.textContent = t('noResults');
      empty.hidden = false;
    } else if (empty) empty.hidden = true;
  }

  // Selected rows float to the top via CSS `order`; these two headers label the groups.
  function updateHeads(onShown, offShown) {
    if (onShown === undefined) {
      onShown = offShown = 0;
      for (const f of FEATURES) {
        const row = els[f.c]?.row;
        if (!row || row.hidden) continue;
        marks.has(f.c) ? onShown++ : offShown++;
      }
    }
    const sel = $('headSel');
    const rest = $('headRest');
    if (!sel || !rest) return;
    sel.textContent = `${t('headSel')} · ${onShown}`;
    sel.hidden = !onShown;
    rest.textContent = t('headRest');
    rest.hidden = !offShown || !onShown;
  }

  /* ---------------- continent filter ---------------- */
  function setRegion(r) {
    activeRegion = activeRegion === r ? null : r;
    for (const f of FEATURES) {
      const off = activeRegion && f.r !== activeRegion;
      for (const s of shapesOf(f.c)) s.classList.toggle('dim', !!off);
    }
    for (const p of map.querySelectorAll('.decor')) p.classList.toggle('dim', !!activeRegion);
    focusBox(activeRegion ? REGION_BOX[activeRegion] : null);
    renderRegions();
    filterList($('search').value);
    list.scrollTop = 0;
  }

  function focusBox(box) {
    scene.classList.add('anim');
    if (!box) {
      view.k = 1;
      view.x = view.y = 0;
    } else {
      const [x0, y0, x1, y1] = box;
      const k = Math.min(MAX_ZOOM, Math.max(1, Math.min(W / (x1 - x0), H / (y1 - y0))));
      view.k = k;
      view.x = W / 2 - ((x0 + x1) / 2) * k;
      view.y = H / 2 - ((y0 + y1) / 2) * k;
    }
    applyView();
    clearTimeout(animTimer);
    animTimer = setTimeout(() => scene.classList.remove('anim'), 450);
  }

  /* ---------------- score ---------------- */
  function updateScore() {
    const s = stats();
    $('count').textContent = s.sov;
    $('total').textContent = `/ ${SOVEREIGN_TOTAL}`;
    $('terr').textContent = s.terr;
    $('pct').textContent = withPct(s.pct);
    $('barfill').style.width = `${(s.sov / SOVEREIGN_TOTAL) * 100}%`;

    $('landPct').textContent = withPct(s.landPct);
    $('landBar').style.width = `${s.landPct}%`;
    $('landAbs').textContent = `${compact(s.land)} km²`;
    $('popPct').textContent = withPct(s.popPct);
    $('popBar').style.width = `${s.popPct}%`;
    $('popAbs').textContent = `${compact(s.people)} ${t('peopleUnit')}`;

    regionCounts = s.per;
    lastCounts = s.byLevel;
    renderBrush(s.byLevel);
    renderRegions();
  }

  function renderBrush(counts) {
    $('brush').replaceChildren(
      ...LEVELS.map((l) => {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = `lvchip lv${l.id}`;
        b.classList.toggle('on', brush === l.id);
        b.setAttribute('aria-pressed', String(brush === l.id));
        const dot = document.createElement('i');
        const name = document.createElement('b');
        name.textContent = t(l.key);
        const n = document.createElement('span');
        n.textContent = counts ? counts[l.id] || 0 : 0;
        b.append(dot, name, n);
        b.onclick = () => {
          brush = l.id;
          renderBrush(lastCounts);
        };
        return b;
      })
    );
  }

  function renderRegions() {
    const chips = REGIONS.map((r) => {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'region';
      btn.classList.toggle('on', activeRegion === r);
      btn.setAttribute('aria-pressed', String(activeRegion === r));
      const b = document.createElement('b');
      b.textContent = REGION_NAMES[lang][r];
      const s = document.createElement('span');
      s.textContent = `${regionCounts[r] || 0}/${REGION_TOTAL[r]}`;
      btn.append(b, s);
      btn.onclick = () => setRegion(r);
      return btn;
    });

    const all = document.createElement('button');
    all.type = 'button';
    all.className = 'region all';
    all.classList.toggle('on', !activeRegion);
    all.setAttribute('aria-pressed', String(!activeRegion));
    const ab = document.createElement('b');
    ab.textContent = t('allRegions');
    const as = document.createElement('span');
    as.textContent = `${$('count').textContent}/${SOVEREIGN_TOTAL}`;
    all.append(ab, as);
    all.onclick = () => activeRegion && setRegion(activeRegion);
    chips.push(all);

    $('regions').replaceChildren(...chips);
  }

  /* ---------------- share card ---------------- */
  const CARD_SIZES = [
    ['link', 'sizeLink'],
    ['square', 'sizeSquare'],
    ['story', 'sizeStory'],
  ];

  function cssVar(name) {
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  }

  function stats() {
    let sov = 0;
    let terr = 0;
    let land = 0;
    let people = 0;
    const per = {};
    const byLevel = { 1: 0, 2: 0, 3: 0, 4: 0 };
    for (const [code, lv] of marks) {
      const f = byCode.get(code);
      if (!f) continue;
      byLevel[lv]++;
      if (!BEEN.has(lv)) continue; // a wish is not a visit
      land += f.k || 0;
      people += f.p || 0;
      if (isCountry(f)) {
        sov++;
        per[f.r] = (per[f.r] || 0) + 1;
      } else terr++;
    }
    return {
      sov,
      terr,
      per,
      byLevel,
      wish: byLevel[4],
      land,
      people,
      total: SOVEREIGN_TOTAL,
      pct: Math.round((sov / SOVEREIGN_TOTAL) * 100),
      landPct: (land / WORLD_LAND) * 100,
      popPct: (people / WORLD_POP) * 100,
    };
  }

  /* ---------------- number formatting ---------------- */
  const compact = (v) =>
    new Intl.NumberFormat(localeOf(), { notation: 'compact', maximumFractionDigits: 1 }).format(v);
  // one decimal below 10% so a single country still registers
  const withPct = (v) =>
    new Intl.NumberFormat(localeOf(), { style: 'percent', maximumFractionDigits: v < 10 ? 1 : 0 }).format(v / 100);

  function shareUrl() {
    return `${location.origin}${location.pathname}#v2=${encodeShare()}`;
  }

  function shareMessage() {
    const s = stats();
    return t('shareText').replace('{n}', s.sov).replace('{total}', s.total).replace('{pct}', withPct(s.pct));
  }

  function buildCardSVG(size) {
    const s = stats();
    const selected = FEATURES.filter((f) => been(f.c) && isCountry(f))
      .map(nameOf)
      .sort((a, b) => a.localeCompare(b, lang));
    return EarthCard.build({
      size,
      world: WORLD,
      marks,
      levels: LEVELS.map((l) => ({ id: l.id, label: t(l.key), count: s.byLevel[l.id], color: cssVar(`--lv${l.id}`) })),
      stats: s,
      regions: REGIONS.map((r) => ({ label: REGION_NAMES[lang][r], have: s.per[r] || 0, total: REGION_TOTAL[r] })),
      names: selected,
      extras: [
        { label: t('land'), value: withPct(s.landPct), sub: `${compact(s.land)} km²`, ratio: s.landPct / 100 },
        { label: t('people'), value: withPct(s.popPct), sub: `${compact(s.people)} ${t('peopleUnit')}`, ratio: s.popPct / 100 },
      ],
      texts: {
        title: t('cardTitle'),
        countries: t('countries'),
        territories: t('territories'),
        pct: withPct(s.pct),
        more: t('cardMore'),
        url: (location.host + location.pathname).replace(/\/(index\.html)?$/, ''),
      },
      colors: {
        bg: cssVar('--bg-2'),
        ocean: cssVar('--ocean'),
        land: cssVar('--land'),
        on: cssVar('--lv2'),
        ink: cssVar('--ink'),
        accent: cssVar('--accent'),
      },
    });
  }

  function svgToPng(svg, scale = 2) {
    return new Promise((resolve, reject) => {
      const size = svg.match(/width="(\d+)" height="(\d+)"/);
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = (size ? +size[1] : img.width) * scale;
        canvas.height = (size ? +size[2] : img.height) * scale;
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
        canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error('toBlob failed'))), 'image/png');
      };
      img.onerror = () => reject(new Error('svg load failed'));
      img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
    });
  }

  async function renderCard() {
    const svg = buildCardSVG(cardSize);
    $('cardImg').src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
    $('cardImg').alt = shareMessage();
    cardBlob = null;
    try {
      cardBlob = await svgToPng(svg, cardSize === 'link' ? 2 : 1.5);
    } catch {
      cardBlob = null;
    }
    updateShareButtons();
  }

  function canSharePng() {
    if (!navigator.canShare || !cardBlob) return false;
    try {
      return navigator.canShare({ files: [new File([cardBlob], 'earthvisited.png', { type: 'image/png' })] });
    } catch {
      return false;
    }
  }

  function updateShareButtons() {
    $('sysShare').hidden = !canSharePng();
    $('saveImg').disabled = !cardBlob;
    $('copyImg').disabled = !cardBlob || !window.ClipboardItem;
  }

  function renderSizes() {
    $('sizes').replaceChildren(
      ...CARD_SIZES.map(([key, label]) => {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = 'size';
        b.classList.toggle('on', cardSize === key);
        b.setAttribute('aria-pressed', String(cardSize === key));
        b.textContent = t(label);
        b.onclick = () => {
          cardSize = key;
          renderSizes();
          renderCard();
        };
        return b;
      })
    );
  }

  function openShare() {
    history.replaceState(null, '', shareUrl());
    cardSize = cardSize || 'link';
    renderSizes();
    renderCard();
    const sheet = $('sheet');
    if (typeof sheet.showModal === 'function') sheet.showModal();
    else sheet.setAttribute('open', '');
  }

  function saveCard() {
    if (!cardBlob) return;
    const href = URL.createObjectURL(cardBlob);
    const a = document.createElement('a');
    a.href = href;
    a.download = `earthvisited-${cardSize}.png`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(href), 5000);
    toast(t('saved'));
  }

  async function copyCard() {
    if (!cardBlob || !window.ClipboardItem) return toast(t('copyImageFail'));
    try {
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': cardBlob })]);
      toast(t('copiedImage'));
    } catch {
      toast(t('copyImageFail'));
    }
  }

  async function systemShare() {
    if (!cardBlob) return;
    const file = new File([cardBlob], 'earthvisited.png', { type: 'image/png' });
    try {
      await navigator.share({ files: [file], text: shareMessage(), url: shareUrl() });
    } catch (err) {
      if (err && err.name === 'AbortError') return;
      try {
        await navigator.share({ text: shareMessage(), url: shareUrl() });
      } catch { /* user dismissed */ }
    }
  }

  /* ---------------- misc UI ---------------- */
  let toastTimer;
  function toast(msg) {
    const el = $('toast');
    el.textContent = msg;
    el.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => (el.hidden = true), 2200);
  }

  async function share() {
    const url = shareUrl();
    history.replaceState(null, '', url);
    try {
      await navigator.clipboard.writeText(url);
      toast(t('copied'));
    } catch {
      toast(t('copyFail'));
    }
  }

  function applyLang() {
    document.documentElement.lang = lang;
    document.title = t('title');
    for (const el of document.querySelectorAll('[data-i18n]')) el.textContent = t(el.dataset.i18n);
    for (const el of document.querySelectorAll('[data-i18n-ph]')) el.placeholder = t(el.dataset.i18nPh);
    for (const el of document.querySelectorAll('[data-i18n-title]')) el.title = t(el.dataset.i18nTitle);
    if (resetArmed) disarmReset();
    if (matchMedia('(hover: none)').matches) $('hint').textContent = t('hintTouch');
    buildList();
    updateScore();
    if ($('settings').open) renderSettings();
    if ($('sheet').open) {
      renderSizes();
      renderCard();
    }
  }

  function disarmReset() {
    clearTimeout(resetTimer);
    resetArmed = false;
    $('resetBtn').textContent = t('reset');
    $('resetBtn').classList.remove('danger');
  }

  function applyTheme() {
    const resolved = theme === 'auto' ? (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark') : theme;
    document.documentElement.dataset.theme = resolved;
    applyColors();
  }

  // Remember what the stylesheet says before any override, so "reset" can restore it.
  function readDefaultColors() {
    for (const l of LEVELS) {
      document.documentElement.style.removeProperty(`--lv${l.id}`);
      DEFAULT_COLORS[l.id] = cssVar(`--lv${l.id}`);
    }
  }

  function applyColors() {
    readDefaultColors();
    for (const l of LEVELS) {
      if (colors[l.id]) document.documentElement.style.setProperty(`--lv${l.id}`, colors[l.id]);
    }
  }

  /* ---------------- settings ---------------- */
  function optionButton(label, active, onPick) {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'opt';
    b.classList.toggle('on', active);
    b.setAttribute('aria-pressed', String(active));
    b.textContent = label;
    b.onclick = onPick;
    return b;
  }

  function renderSettings() {
    $('langOpts').replaceChildren(
      ...LANGS.map((l) =>
        optionButton(l.label, lang === l.code, () => {
          lang = l.code;
          savePrefs();
          applyLang();
          renderSettings();
        })
      )
    );

    $('themeOpts').replaceChildren(
      ...['dark', 'light', 'auto'].map((mode) =>
        optionButton(t(mode), theme === mode, () => {
          theme = mode;
          savePrefs();
          applyTheme();
          renderSettings();
        })
      )
    );

    $('colorList').replaceChildren(
      ...LEVELS.map((l) => {
        const row = document.createElement('label');
        row.className = 'colorrow';
        const swatch = document.createElement('input');
        swatch.type = 'color';
        swatch.value = colors[l.id] || DEFAULT_COLORS[l.id] || '#34d399';
        swatch.oninput = () => {
          colors[l.id] = swatch.value;
          applyColors();
          savePrefs();
          repaintLevelColors();
        };
        const name = document.createElement('b');
        name.textContent = t(l.key);
        const count = document.createElement('span');
        count.textContent = lastCounts ? lastCounts[l.id] || 0 : 0;
        row.append(swatch, name, count);
        return row;
      })
    );
  }

  // colours live in CSS variables, so only the pieces drawn from JS need a nudge
  function repaintLevelColors() {
    renderBrush(lastCounts);
    if ($('sheet').open) renderCard();
  }

  function init() {
    loadPrefs();
    load();
    applyTheme();
    buildMap();
    applyView();
    initZoom();
    applyLang();
    for (const code of marks.keys()) paintShape(code);

    $('search').addEventListener('input', (e) => filterList(e.target.value));
    $('search').addEventListener('keydown', (e) => {
      if (e.key !== 'Enter') return;
      const row = [...list.querySelectorAll('.row')].find((r) => !r.hidden);
      if (row) {
        toggle(row.dataset.code);
        e.target.select();
      }
    });
    // two-step reset instead of a browser confirm(): the second tap does it
    $('resetBtn').onclick = () => {
      if (!marks.size) return;
      if (!resetArmed) {
        resetArmed = true;
        $('resetBtn').textContent = t('resetAsk');
        $('resetBtn').classList.add('danger');
        clearTimeout(resetTimer);
        resetTimer = setTimeout(disarmReset, 3500);
        return;
      }
      disarmReset();
      const all = [...marks.keys()];
      marks.clear();
      all.forEach(paintShape);
      all.forEach(paintRow);
      updateScore();
      save();
    };
    $('settingsBtn').onclick = () => {
      renderSettings();
      const dlg = $('settings');
      if (typeof dlg.showModal === 'function') dlg.showModal();
      else dlg.setAttribute('open', '');
    };
    $('settingsClose').onclick = () => $('settings').close();
    $('settings').addEventListener('click', (e) => {
      if (e.target === $('settings')) $('settings').close();
    });
    $('resetColors').onclick = () => {
      colors = {};
      applyColors();
      savePrefs();
      renderSettings();
      repaintLevelColors();
    };
    matchMedia('(prefers-color-scheme: light)').addEventListener('change', () => {
      if (theme === 'auto') applyTheme();
    });

    $('shareBtn').onclick = openShare;
    $('sheetClose').onclick = () => $('sheet').close();
    $('sheet').addEventListener('click', (e) => {
      if (e.target === $('sheet')) $('sheet').close(); // click on the backdrop
    });
    $('copyLink').onclick = share;
    $('saveImg').onclick = saveCard;
    $('copyImg').onclick = copyCard;
    $('sysShare').onclick = systemShare;
    addEventListener('resize', sizeMarkers);
    addEventListener('hashchange', () => {
      const codes = fromHash();
      if (!codes) return;
      const touched = new Set([...marks.keys(), ...codes.map(([c]) => c)]);
      marks.clear();
      codes.forEach(([c, lv]) => byCode.has(c) && marks.set(c, lv));
      touched.forEach(paintShape);
      touched.forEach(paintRow);
      updateScore();
      save();
    });
  }

  document.addEventListener('DOMContentLoaded', init);
})();
